bin/mm: make bootimage for sepolicy bin/my-rsync: should support smb:// bin/overide/my-adb: do not wait for device anymore bin/update-repo-projects: only fast-forward
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/abc b/bin/abc
--- a/bin/abc
+++ b/bin/abc
@@ -992,6 +992,32 @@ EOF
     ssh -i ~/.ssh/id_rsa_cmtest cmtest@code -p 29418 gerrit review "$review_patch" --verified $verified -m \'"${message//\'/\'\\\'\'}"\'
 }
 
+function abc-beagrep() {
+    ## start code-generator "^\\s *#\\s *"
+    # generate-getopts -l b:base_build
+    ## end code-generator
+    ## start generated code
+    local base_build=
+    local OPTIND=1
+    while getopts 'b:' opt; do
+        case "$opt" in
+            b)    base_build=$OPTARG;;
+            *)    echo Usage Error; exit 2;;
+        esac
+    done
+    shift $(($OPTIND - 1))
+    
+    ## end generated code
+    
+    base_build=${base_build#*/}
+    base_build=~/buildfarm/$base_build
+    if test ! -d "$base_build" || ! is-a-subdir "$base_build" ~/buildfarm/; then
+        die "Invalid repo dir: $repo_path"
+    fi
+    cd "$base_build"
+    beagrep "$@"
+}
+
 function abc-files() { # use beagrep to find matching files, for e.g.,
                        # abc-files "readlink" will list all files that
                        # contains readlink.
