.bashrc-public: code refactory .bashrc-remote: fix WHOAMI .bashrc-ssh-agent: use different file for 2 sshd on one PC .emacs_d/yasnippet/snippets/sh-mode/diedef.yasnippet: die should use stderr .git-exclude: do not exclude qc_version.o bin/Linux/putclip: use different port bin/abc-user: use die bin/adb-backup-system: fix ~/etc; should not sync debian bin/adb-clean-data: make sure won't run on my main phone, and do not remove apps bin/android-make: fix android-make to use mmma bin/android-manifest-diff: make it useful for qualcomm upgrade bin/android-rsync-phone-ota: should use the lolipop version of gms bin/do-firefox-login-page: add chipcode support bin/git-push-rebase: code reuse bin/notify-phone-crash: fix gms app location bin/redo-ssh-agent: code reuse bin/remote-putclip: allow using on port other than 22 bin/repo-cherry-find-all: fix it for qualcomm upgrade bin/repo-cherry-pick-all: allow to quit as early as possible using "exit 4" bin/repo-switch: make repo-switch -p sharable bin/test-freq-current-temp.sh: should use the right number of cpus bin/update-repo-projects: code reuse etc/adb-sync-data-exclude: should not backup debian
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/abc-user b/bin/abc-user
--- a/bin/abc-user
+++ b/bin/abc-user
@@ -8,13 +8,17 @@ set -e
 who=${0##*abc-}
 export ABC_USER=$who
 
+function die() {
+    echo Error: "$@" 1>&2
+    exit -1
+}
+
 if echo "$SSH_ORIGINAL_COMMAND" | grep -o -P -e '[^-a-z0-9:./_ ]+' -i; then
-   echo "The above characters are not allowed"
-   exit 1
+    die "The above characters are not allowed"
 fi
 
 if test "$(echo "$SSH_ORIGINAL_COMMAND" | pn 1)" != abc; then
-   echo Android Build Cake: "$(echo "$SSH_ORIGINAL_COMMAND" | pn 1)": not found
+    die Android Build Cake: "$(echo "$SSH_ORIGINAL_COMMAND" | pn 1)": command not found.
 fi
 
 
diff --git a/bin/adb-clean-data b/bin/adb-clean-data
--- a/bin/adb-clean-data
+++ b/bin/adb-clean-data
@@ -1,9 +1,18 @@
 #!/bin/bash
+set -e
 my-adb -r stop
+
+if test -z "$ANDROID_SERIAL"; then
+    die "Can't do it without ANDROID_SERIAL set"
+fi
+
+if test "$ANDROID_SERIAL" = a2024058; then
+    die "Must not run it on a2024058"
+fi
 
 my-adb 'cd /data;
         for x in *; do
-            if test $x = media -o $x = debian -o $x = misc -o $x = property; then
+            if test $x = media -o $x = app -o $x = debian -o $x = misc -o $x = property; then
                 continue;
             else
                 rm -r $x;
