.bash_completion.d/adb.bash: fix completion for white spaces in filename .bashrc: add per pc customization bin/adb-browse-with-pc: fix weixin browse with pc bin/adb-get-a-note: get a note from t1 bin/adb-get-last-pic: allow remove the pic after get it, and redirect output so to be usable bin/adb-search-contact: search for contact, to work around it always lost after click in bin/adb-settings: add more settings bin/adb-start-vpn: start the vpn without waiting bin/adb-weixin-choose-chatter: optimization bin/adb-weixin-choose-chatter: make 黄 波 to 黄.*波 bin/after-co-ln-s.sh: do not replace it blindly bin/do-remote-system-config: should not do system config sometimes, only copy the id_rsas bin/overide/adb: add a start-activity sub command bin/smb2ftp: smbcp first, then lftp bin/vm: reverse mv
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/adb-get-last-pic b/bin/adb-get-last-pic
--- a/bin/adb-get-last-pic
+++ b/bin/adb-get-last-pic
@@ -1,24 +1,52 @@
 #!/bin/bash
+TEMP=$(getopt -o r --long remove -n $(basename $0) -- "$@")
+remove=false
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+        -r|--remove)
+            remove=true
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error: $@"
+            ;;
+    esac
+done
 
-dir=/sdcard/DCIM/Camera
-
-if test "$1" = c; then
+{
     dir=/sdcard/DCIM/Camera
-elif test "$1" = m; then
-    dir=/sdcard/Download/mail_attachments/
-elif test "$1" = s; then
-    dir=/sdcard/Pictures/Screenshots/
-elif test "$1" = d; then
-    dir=/sdcard/Download/
-elif test "$1"; then
-    echo should be one of '"msd"'
-fi
 
-pic=$(adb busybox ls -t -1 $dir|head -n 1|perl -npe 's/\033.*?m//g; s/\?+/*/g')
-if [[ $pic =~ \* ]]; then
-    pic=$(adb bash -c "ls $dir/$pic"|perl -npe 's!.*/!!')
-fi
-cd ~/Pictures/
-adb pull $dir/$pic
+    if test "$1" = c; then
+        dir=/sdcard/DCIM/Camera
+    elif test "$1" = m; then
+        dir=/sdcard/Download/mail_attachments/
+    elif test "$1" = s; then
+        dir=/sdcard/Pictures/Screenshots/
+    elif test "$1" = n; then
+        dir=/sdcard/smartisan/Notes
+    elif test "$1" = d; then
+        dir=/sdcard/Download/
+    elif test "$1"; then
+        echo should be one of '"msd"'
+    fi
+
+    pic=$(adb busybox ls -t -1 $dir|head -n 1|perl -npe 's/\033.*?m//g; s/\?+/*/g')
+    if [[ $pic =~ \* ]]; then
+        pic=$(adb bash -c "ls $dir/$pic"|perl -npe 's!.*/!!')
+    fi
+    cd ~/Pictures/
+    adb pull $dir/$pic
+    if test $remove = true; then
+        adb rm $dir/$pic
+        adb am startservice -n com.bhj.setclip/.PutClipService --es picture $dir/$pic
+    fi
+} 1>&2
 up $pic
-of $pic
+if is-tty-io; then
+    of $pic >/dev/null 2>&1
+fi
