.emacs_d/yasnippet/snippets/sh-mode/me: add set -e bin/adb-tap: should use adb-tap as adb-long-press
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/adb-tap b/bin/adb-tap
--- a/bin/adb-tap
+++ b/bin/adb-tap
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
+
+if test "$b0" != adb-tap; then
+    set -- $b0 "$@"
+fi
+
 . ~/src/github/smartcm/scm-helpers/.adb-get-screen-size
 export width=1080
 export height=1920
