.globalrc: add scala support bin/adb-backup-system: add chcon support bin/adb-install-debian: should not use sdcard, because maybe adb-stop-all-services bin/android-rsync-phone-ota: should do sync bin/start-http-proxy: fix it for some java apps etc/adb-sync-data-exclude: should not exclude the cache files, will need re-install on 8992
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/adb-install-debian b/bin/adb-install-debian
--- a/bin/adb-install-debian
+++ b/bin/adb-install-debian
@@ -1,6 +1,16 @@
 #!/bin/bash
 
 set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+
 if test ! -e /sbin/adbd; then # 没有adbd文件，在PC上而不是手机上
     if test ! -d ~/external/debian; then
         mkdir -p ~/external/
@@ -26,8 +36,8 @@ if test ! -e /sbin/adbd; then # 没有adbd文件，在PC上而不是手机上
         my-adb 'cd /data; mv deb.tgz debian.tgz; tar zxvf debian.tgz'
     fi
 
-    my-adb -r push $0 /sdcard/$(basename $0) # 把我自己push到手机上
-    my-adb bash -x /sdcard/$(basename $0) # 并执行这个 if ... fi 后面的内容
+    my-adb -r push $me /data/$(basename $0) # 把我自己push到手机上
+    my-adb bash -x /data/$(basename $0) # 并执行这个 if ... fi 后面的内容
 
     my-adb chroot /data/debian /bin/bash -c "
     export LD_PRELOAD=
@@ -68,6 +78,7 @@ EOF
     echo en_US.UTF-8 UTF-8 > /etc/locale.gen
     locale-gen
     echo LANG=en_US.UTF-8 > /etc/default/locale
+    ln -s /data/media/0 /sdcard
 "
     my-adb -r stop
     my-adb shell sync
diff --git a/bin/android-rsync-phone-ota b/bin/android-rsync-phone-ota
--- a/bin/android-rsync-phone-ota
+++ b/bin/android-rsync-phone-ota
@@ -48,8 +48,8 @@ fi
 my-adb -r id | grep 'uid=0\b'
 
 if test $no_system = false; then
-    if ! my-adb 'test -d /data/debian/ && echo -n hello && echo '$$ | grep hello$$ -q; then
-        die "Debian not found on this phone, can't use rsync"
+    if ! my-adb 'test -d /data/debian/ && which bash && echo -n hello && echo '$$ | grep hello$$ -q; then
+        die "Debian or bash not found on this phone, can't use rsync"
     fi
     ssh-to-phone echo hello$$ | grep hello$$
 fi
@@ -163,7 +163,8 @@ fi
 sudo rsync . root@phone:/system -av --delete-before --exclude media/app --delete-excluded
 sudo find ../system -type l -prune -o -print |sort |sudo xargs ls -Zd |grep -v 'u:object_r:system_file:s0\|\?'|perl -npe 's/^/chcon /' |tee ../system.chcon
 my-adb push ../system.chcon /data/
-my-adb 'cd /system; bash -x /data/system.chcon'
+my-adb 'cd /system; bash -x /data/system.chcon; sync'
+my-adb romount
 cd ..
 sudo umount system
 cd ..
