Try to fix install-debian.
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/adb-install-debian b/bin/adb-install-debian
--- a/bin/adb-install-debian
+++ b/bin/adb-install-debian
@@ -1,18 +1,9 @@
 #!/bin/bash
 
+# [[file:~/system-config/knuth-mode/adb-install-debian.org::*%E6%9C%80%E7%BB%88%E7%9A%84%E7%89%88%E6%9C%AC%EF%BC%9A][the-ultimate-script]]
+
 set -e
-
-me=$(readlink -f $0)
-if test ! -e "$me"; then
-    me=$(readlink -f "$(which $0)")
-    if test ! -e "$me"; then
-        die "Can't find out about me"
-        exit 1
-    fi
-fi
-b0=$(basename $0)
-
-if test ! -e /sbin/adbd; then # 没有adbd文件，在PC上而不是手机上
+local-pc-script() {
     ## start code-generator "^\\s *#\\s *"
     # generate-getopt @:arch=arm64 @:mirror=http://deb.debian.org/debian
     ## end code-generator
@@ -77,61 +68,66 @@ if test ! -e /sbin/adbd; then # 没有adbd文件，在PC上而不是手机上
     fi
 
     adb-fix-busybox
-    if ! my-adb "test -d /data/debian.$arch && echo yes$$" | grep -q yes$$; then
+    if ! my-adb "test -d /data/debian.$arch"; then
         my-adb -r push ~/external/debian.$arch.tgz /data/deb.tgz
         my-adb sc-shell "cd /data; mv deb.tgz debian.tgz; tar zxvf debian.tgz; rm -f /data/debian; ln -s /data/debian.$arch /data/debian"
     fi
 
-    my-adb -r push $me /data/$(basename $0) # 把我自己push到手机上
-    my-adb sc-shell bash -x /data/$(basename $0) 2>&1 | tee ~/tmp/$b0.log # 并执行这个 if ... fi 后面的内容
-
-    if ! grep "every thing is ok" -q ~/tmp/$b0.log; then
-        die "Can't get everything ok, please check ~/tmp/$b0.log"
+    my-adb -r push $me /data/$(basename $0) # 把我自己 push 到手机上
+    if ! my-adb sc-shell bash -e -x /data/$(basename $0) 2>&1; then
+        die "Can't run this script's on-phone part, please check the above output"
     fi
 
-    my-adb sc-shell chroot /data/debian.$arch /bin/bash -c "
-    export LD_PRELOAD=
-    export PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PATH
-    export HOME=/root
-    set -x
-    set -e
-    if test ! -e /second-stage-done; then
-        /debootstrap/debootstrap --second-stage
-        touch /second-stage-done
-    fi
-    echo deb http://ftp.us.debian.org/debian testing main contrib non-free > /etc/apt/sources.list
-    if ! grep 192.168.15.33 /etc/hosts -q; then
-        echo 192.168.15.33 pc >> /etc/hosts
-    fi
+    my-adb sc-shell chroot /data/debian.$arch /bin/bash -c "$(cat <<EOFa3616cfa6b68
+export LD_PRELOAD=
+export PATH=/bin:/usr/bin:/sbin:/usr/sbin:\$PATH
+export HOME=/root
+set -x
+set -e
+if test -e /debian-ok; then
+    exit
+fi
+if test ! -e /second-stage-done; then
+    /debootstrap/debootstrap --second-stage
+    touch /second-stage-done
+fi
+echo deb http://ftp.us.debian.org/debian testing main contrib non-free > /etc/apt/sources.list
+if ! grep 192.168.15.33 /etc/hosts -q; then
+    echo 192.168.15.33 pc >> /etc/hosts
+fi
 
-    addgroup $USER --gid 1000 || true
-    addgroup --gid 1023 media_rw || true
-    addgroup --gid 1015 android_sdcard_rw || true
-    addgroup --gid 3003 android_inet || true
+addgroup $USER --gid 1000 || true
+addgroup --gid 1023 media_rw || true
+addgroup --gid 1015 android_sdcard_rw || true
+addgroup --gid 3003 android_inet || true
 
-    addgroup android_inet --gid 3003 || true
-    addgroup android_sdcard_rw --gid 1015 || true
-    adduser --gecos '' --disabled-password $USER --uid 1000 --gid 1000 || true
-    adduser --gecos '' --disabled-password media_rw --uid 1023 --gid 1023 || true
+addgroup android_inet --gid 3003 || true
+addgroup android_sdcard_rw --gid 1015 || true
+adduser --gecos '' --disabled-password $USER --uid 1000 --gid 1000 || true
+adduser --gecos '' --disabled-password media_rw --uid 1023 --gid 1023 || true
 
-    usermod $USER -a -G android_inet,android_sdcard_rw,media_rw || true
-    usermod -g android_inet _apt || true
-    cd
-    umask 0022
-    mkdir -p ~/.ssh
-    mkdir -p ~$USER/.ssh
-    mkdir -p ~media_rw/.ssh
-    chown $USER\. ~$USER/.ssh -R
-    cat <<EOF > /etc/resolv.conf
+usermod $USER -a -G android_inet,android_sdcard_rw,media_rw || true
+usermod -g android_inet _apt || true
+cd
+umask 0022
+mkdir -p ~/.ssh
+mkdir -p ~$USER/.ssh
+mkdir -p ~media_rw/.ssh
+chown $USER\. ~$USER/.ssh -R
+cat <<EOF > /etc/resolv.conf
 nameserver $(my-adb getprop net.dns1)
 EOF
-    ln -sf /android/* /
-    echo en_US.UTF-8 UTF-8 > /etc/locale.gen
-    locale-gen
-    echo LANG=en_US.UTF-8 > /etc/default/locale
-    ln -s /data/media/0 /sdcard
-    apt-get clean
-"
+ln -sf /android/* /
+echo en_US.UTF-8 UTF-8 > /etc/locale.gen
+locale-gen
+echo LANG=en_US.UTF-8 > /etc/default/locale
+ln -s /data/media/0 /sdcard
+apt-get clean
+touch /debian-ok
+
+
+EOFa3616cfa6b68
+)"
     my-adb -r stop
     my-adb shell sync
     if test ! -e ~/.ssh/authorized_keys; then
@@ -156,52 +152,76 @@ EOF
     my-adb chmod 600 /data/debian/home/media_rw/.ssh/authorized_keys
 
     my-adb forward tcp:22222 tcp:22
-    exit
+}
+  # 这些是在手机上执行的内容
+function prepare-chroot() {
+    mount -o remount /data # rm the nodev flag
+
+    if [ ! -d /tmp ]; then
+        mount -o rw,remount / && mkdir /tmp && chmod 1777 /tmp && mount -o ro,remount /
+    fi
+    if [ ! -f /tmp/.mounted ] ; then
+        mount -t tmpfs none /tmp && touch /tmp/.mounted
+    fi
+
+    # setup posix shared memory
+    if [ ! -d /dev/shm ] ; then mkdir /dev/shm ; fi
+    chmod 1777 /dev/shm
+    if mount | grep /dev/shm; then
+        true
+    else
+        mount -t tmpfs none /dev/shm/
+    fi
+
+    # configure debian chroot
+    if [ -d /data/debian/proc ] && [ ! -d /data/debian/proc/1 ] ; then
+        mount -o bind /proc /data/debian/proc
+    fi
+
+    if [ -d /data/debian/sys ] && [ ! -d /data/debian/sys/class ] ; then
+        mount -o bind /sys /data/debian/sys
+    fi
+
+    if [ -d /data/debian/sys/kernel/debug ] && [ ! -d /data/debian/sys/kernel/debug/tracing ] ; then
+        mount -o bind /sys/kernel/debug/ /data/debian/sys/kernel/debug
+    fi
+
+    if test ! -e /data/debian/dev/null || test -e /data/debian/dev/.dev-not-mounted -o -f /data/debian/dev/null; then
+        mount -o bind /dev /data/debian/dev
+        mount -o bind /dev/pts /data/debian/dev/pts
+        mount -o bind /dev/shm /data/debian/dev/shm
+        for x in system data cache factory d acct; do
+            if test ! -e /$x; then
+                continue
+            fi
+            mkdir -p /data/debian/android/$x
+            mount -o bind /$x /data/debian/android/$x
+        done
+    fi
+}
+
+#!/bin/bash
+
+set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
+
+if test ! -e /sbin/adbd; then # 没有 adbd 文件，在 PC 上而不是手机上
+    local-pc-script
+else # on the phone
+    prepare-chroot
 fi
 
-# 这些是在手机上执行的内容
+# Local Variables: #
+# eval: (read-only-mode 1) #
+# End: #
 
-mount -o remount /data # rm the nodev flag
-
-if [ ! -d /tmp ]; then
-    mount -o rw,remount / && mkdir /tmp && chmod 1777 /tmp && mount -o ro,remount /
-fi
-if [ ! -f /tmp/.mounted ] ; then
-    mount -t tmpfs none /tmp && touch /tmp/.mounted
-fi
-
-# setup posix shared memory
-if [ ! -d /dev/shm ] ; then mkdir /dev/shm ; fi
-chmod 1777 /dev/shm
-if mount | grep /dev/shm; then
-    true
-else
-    mount -t tmpfs none /dev/shm/
-fi
-
-# configure debian chroot
-if [ -d /data/debian/proc ] && [ ! -d /data/debian/proc/1 ] ; then
-   mount -o bind /proc /data/debian/proc
-fi
-
-if [ -d /data/debian/sys ] && [ ! -d /data/debian/sys/class ] ; then
-    mount -o bind /sys /data/debian/sys
-fi
-
-if [ -d /data/debian/sys/kernel/debug ] && [ ! -d /data/debian/sys/kernel/debug/tracing ] ; then
-    mount -o bind /sys/kernel/debug/ /data/debian/sys/kernel/debug
-fi
-
-if test ! -e /data/debian/dev/null || test -e /data/debian/dev/.dev-not-mounted -o -f /data/debian/dev/null; then
-   mount -o bind /dev /data/debian/dev
-   mount -o bind /dev/pts /data/debian/dev/pts
-   mount -o bind /dev/shm /data/debian/dev/shm
-   for x in system data cache factory d acct; do
-       if test ! -e /$x; then
-           continue
-       fi
-       mkdir -p /data/debian/android/$x
-       mount -o bind /$x /data/debian/android/$x
-   done
-fi
-echo every thing is ok
+# the-ultimate-script ends here
