Continue to move from system-config to ajoke
Signed-off-by: Bao Haojun <hjbao@marvell.com>

diff --git a/bin/ajoke b/bin/ajoke
--- a/bin/ajoke
+++ b/bin/ajoke
@@ -8,31 +8,23 @@ function die() {
 }
 
 me=$(readlink -f $0)
-if test "$me" != ~/system-config/bin/ajoke; then
-    die "ajoke not found at ~/system-config/bin/ajoke, please run:
-    cd ~; git clone --recursive http://github.com/baohaojun/system-config"
+ajoke_bindir=$(dirname $me)
+ajoke_dir=$(dirname $ajoke_bindir)
+
+if test ! -e $ajoke_dir/etc/perl/BhjJava.pm; then
+    die "$ajoke_dir/etc/perl/BhjJava.pm not found,
+incorrect git clone? Please run:
+    git clone --recursive http://github.com/baohaojun/ajoke"
 fi
 
+perl5d=$HOME/perl5
 
-if test -x /opt/local/libexec/gnubin/readlink; then
-    # on MacOS, the system readlink doesn't do -m/-f options
-    export PATH=/opt/local/libexec/gnubin:$PATH
-fi
-if test -d ~/system-config/etc/path/$(uname)-$(uname -m); then
-    rm -rf ~/external/etc/overide/
-    export PATH=$(
-        builtin cd ~/system-config/etc/path/$(uname)-$(uname -m);
-        for x in $(for d in *; do echo $d; done|sort -n); do
-            readlink -m -- $x;
-        done|tr '\n' ':'
-    ):$PATH
-fi
-
-export PERL_LOCAL_LIB_ROOT="$HOME/perl5";
-export PERL_MB_OPT="--install_base $HOME/perl5";
-export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5";
-export PERL5LIB="$HOME/perl5/lib/perl5/x86_64-linux-gnu-thread-multi:$HOME/perl5/lib/perl5:$HOME/system-config/etc/perl:$PERL5LIB";
-export PATH="$HOME/perl5/bin:$PATH";
+export PATH=$ajoke_bindir:$PATH
+export PERL_LOCAL_LIB_ROOT="$perl5d";
+export PERL_MB_OPT="--install_base $perl5d";
+export PERL_MM_OPT="INSTALL_BASE=$perl5d";
+export PERL5LIB="$perl5d/lib/perl5/x86_64-linux-gnu-thread-multi:$perl5d/lib/perl5:$ajoke_dir/etc/perl:$PERL5LIB";
+export PATH="$perl5d/bin:$PATH";
 
 
 function test-env() {
@@ -50,32 +42,57 @@ function test-env() {
         cpan Text::Glob
     fi
 
-    if test ! -x /usr/local/bin/global; then
+    if ! global --version | grep -i 'Patched for ajoke'; then
         if yes-or-no-p "You have not built ajoke's version of GNU gtags,
-build it with compile_gtags (will need sudo for installing)?"; then
-            compile_gtags
+build it now (will need sudo for installing)?"; then
+            (
+                cd $ajoke_dir
+                cd ./external/global
+                sh ./reconf.sh
+                ./configure
+                make -j8
+                sudo make install
+            )
         else
             die "ajoke's gtags not built"
         fi
     fi
 
-    if test -b /usr/bin/ctags-exuberant; then
-        if yes-or-no-p "You need to install ctags-exuberant, apt-get?"; then
-            sudo apt-get install ctags-exuberant
+    if ! ctags-exuberant --version; then
+        if yes-or-no-p "You need to install ctags-exuberant, run apt-get now?"; then
+            sudo apt-get install exuberant-ctags
         else
             die "Can't use ctags-exuberant"
         fi
     fi
 
-    if test ! -e ~/.globalrc || ! diff -q ~/.globalrc ~/system-config/.globalrc; then
-        if yes-or-no-p "You need use ajoke's version of .globalrc, replace?"; then
-            if test -e ~/.globalrc; then
-                mv ~/.globalrc ~/.globalrc.bak
-            fi
-            relative-link ~/system-config/.globalrc ~/
-        else
-            die "ajoke's version of .globalrc not used"
-        fi
+    global_path=$(which global)
+
+    if test -z "$global_path"; then
+        die "global still not found after build";
     fi
 
+    global_prefix=$(dirname $(dirname $global_path))
+    gtags_conf_in=$ajoke_dir/external/global/gtags.conf.in
+
+    perl -npe "s,\@prefix\@,$global_prefix,g" $gtags_conf_in > ~/.globalrc
+    ln -sf $ajoke_dir/etc/.ctags ~/
+
+    javac_path=$(which javac)
+    if test -z "$javac_path"; then
+        die "javac not found, please install: sudo apt-get install openjdk-6-jdk"
+    fi
+    java_dir=$(dirname $(dirname $javac_path))
+    if test -e ~/.cache/for-code-reading/$java_dir/GTAGS; then
+        echo "Good, you have done mkgtags for java"
+    else
+        (
+            cd $java_dir
+            mkgtags
+        )
+    fi
 }
+
+if test $# != 0; then
+    "$@"
+fi
