debian on android: update for jelly bean. repo script hook.

diff --git a/bin/android-hourly-build b/bin/android-hourly-build
--- a/bin/android-hourly-build
+++ b/bin/android-hourly-build
@@ -11,6 +11,13 @@ cd $(lookup_file .repo/..)
 start_hour=$(date +%H)
 test -d .repo || die ".repo not found, not android source directory?"
 
+if test "$DO_NOT_GQ_REBASE" = true; then
+    hourly_log=hourly-build-without-rebase.log
+else
+    hourly_log=hourly-build.log
+fi
+
+
 exec 9>.android-full-build.lock
 flock 9
 
@@ -18,14 +25,42 @@ flock 9
     set -x
     rm -f .build-started
     if yes-or-no-p -y "Do sync?"; then
-        my-rfa 'git reset --hard; git clean -xfd' || true
-        repo sync -j4 -d || die "repo sync failed"
-        bpe-update -r
-        my-rfa '
-            if test -e $ANDROID_TOP/flashing/quilt/$(repo-tracking)/$(repo-path)/series && gq next | grep -q .; then
-                echo Error: $(pwd) guilt not cleanly applied
+        if test "$DO_NOT_GQ_REBASE" = true; then
+            # only need reset those local patch rebased
+            my-rfa '
+                if test -e $ANDROID_TOP/flashing/quilt/$(repo-tracking)/$(repo-path)/series; then
+                    git reset --hard $(repo-remote-branch)
+                    git clean -xfd
+                fi
+            '
+        else
+            my-rfa 'git reset --hard; git clean -xfd' || true
+            if test "$LOCAL_SYNC" = true; then
+                repo sync -j4 -d -l
+            else
+                repo-sync -j4 -d 
+            fi || die "Error: repo sync failed" | tee build.log
+        fi
+
+        if test ! -e .do_not_gq_rebase -a "$DO_NOT_GQ_REBASE" != true; then
+            {
+                bpe-update -r
+                my-rfa '
+                    if test -e $ANDROID_TOP/flashing/quilt/$(repo-tracking)/$(repo-path)/series && gq next | grep -q .; then
+                        echo Error: $(pwd) guilt not cleanly applied
+                    fi
+                ' | grep . && export DO_NOT_GQ_REBASE=true
+            } > build.log-rebase
+
+            if test "$DO_NOT_GQ_REBASE" = true; then
+                flock -u 9
+                android-hourly-build "$@" || true
+                rm daily-changes/* -rf
+                mv build.log-rebase build.log
+                die "Error: guilt rebase not cleanly applied; need bail out."
             fi
-        ' | grep . && die "Error: guilt rebase not cleanly applied; need bail out." > build.log
+        fi
+            
     fi
     
     touch .build-started
@@ -33,7 +68,7 @@ flock 9
     android-full-build "$@" || die "android-full-build failed"
     touch .build_ok
     rm .build_failed -fr
-) > hourly-build.log 2>&1 || (
+) > $hourly_log 2>&1 || (
 
     if test "$start_hour" = 6; then #maybe need do a full clean build next time.
         rm ../$(basename $(pwd))-out/out-* -rf
@@ -58,6 +93,7 @@ flock 9
         rm .build_ok
         last_time_build_ok=yes
     fi
-    tar cz $daily_change_dir build.log hourly-build.log | gerrit-review-mail-it build-failed last_time_build_ok=$last_time_build_ok "$@"
+    tar cz $daily_change_dir build.log $hourly_log | gerrit-review-mail-it build-failed last_time_build_ok=$last_time_build_ok "$@" || true
+    rm $daily_change_dir -rf
 
 )
