bin/adb-install-debian: do not prompt for name/address etc bin/android-rsync-phone-ota: check for debian bin/bindiff.py: print more meaningful log bin/gpt-part-parser.pl: print aligning to sbl code
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/android-rsync-phone-ota b/bin/android-rsync-phone-ota
--- a/bin/android-rsync-phone-ota
+++ b/bin/android-rsync-phone-ota
@@ -24,6 +24,10 @@ if test ! -e "$xml"; then
 fi
 
 my-adb -r id | grep 'uid=0\b'
+
+if ! my-adb 'test -d /data/debian/ && echo -n hello && echo '$$ | grep hello$$ -q; then
+    die "Debian not found on this phone, can't use rsync"
+fi
 ssh-to-phone echo hello$$ | grep hello$$
 
 function update-partition() {
