Update android-full-build timing.

diff --git a/bin/android-full-build b/bin/android-full-build
--- a/bin/android-full-build
+++ b/bin/android-full-build
@@ -67,36 +67,38 @@ fi
 test -e buildspec.mk || { echo no buildspec.mk, will exit now; exit; }
 
 (
-    touch .for-code-reading
-    echo 'about to lock at '$(date)
-    flock 9 || { echo 'lock failed at '$(date); exit -1; }
-    echo 'lock success! at '$(date)
-    (
-	echo "before build, ccache stat is $(./prebuilt/linux-x86/ccache/ccache -s)"
-	echo "external dirs not managed by repo: $(repo-external)"
-	echo "changed repos are: $(repo-changes\?)"
-    )&
-    result=''
-    if test "$target" = all; then
-	time $(which time) make -j$jobs -l$jobs -k droid telephony uboot obm && result=$result'all ok; '
-    fi
-    if [[ "$target" =~ kernel ]]; then
-	command time make -k kernel && result=$result'kernel ok; '
-    fi
-    
-    if [[ "$target" =~ system ]]; then
-	command time make -j$jobs -l$jobs -k && result=$result'android ok; '
-    fi
-    if [[ "$target" =~ misc ]]; then
-	command time make -k telephony uboot obm && result=$result'misc ok; '
-    fi
-    echo "$result"
-    (
-	cd flashing
-	./make-links.sh
-	./copy-release.sh .
-	find . -type l -print0 |xargs -0 bash -c 'for x in "$@"; do chmod a+r "$(readlink -m "$x")"; done' true 
-    ) >/dev/null 2>&1 
-    echo -n 'after build, ccache stat is '
-    ./prebuilt/linux-x86/ccache/ccache -s
+    time (
+	touch .for-code-reading
+	echo 'about to lock at '$(date)
+	flock 9 || { echo 'lock failed at '$(date); exit -1; }
+	echo 'lock success! at '$(date)
+	(
+	    echo "before build, ccache stat is $(./prebuilt/linux-x86/ccache/ccache -s)"
+	    echo "external dirs not managed by repo: $(repo-external)"
+	    echo "changed repos are: $(repo-changes\?)"
+	)&
+	result=''
+	if test "$target" = all; then
+	    time $(which time) make -j$jobs -l$jobs -k droid telephony uboot obm && result=$result'all ok; '
+	fi
+	if [[ "$target" =~ kernel ]]; then
+	    command time make -k kernel && result=$result'kernel ok; '
+	fi
+	
+	if [[ "$target" =~ system ]]; then
+	    command time make -j$jobs -l$jobs -k && result=$result'android ok; '
+	fi
+	if [[ "$target" =~ misc ]]; then
+	    command time make -k telephony uboot obm && result=$result'misc ok; '
+	fi
+	echo "$result"
+	(
+	    cd flashing
+	    ./make-links.sh
+	    ./copy-release.sh .
+	    find . -type l -print0 |xargs -0 bash -c 'for x in "$@"; do chmod a+r "$(readlink -m "$x")"; done' true 
+	) >/dev/null 2>&1 
+	echo -n 'after build, ccache stat is '
+	./prebuilt/linux-x86/ccache/ccache -s
+    )
 ) 9>~/.logs/android-full-build.lock  2>&1 | tee build.log
