Android build script.

diff --git a/bin/android-daily-changes b/bin/android-daily-changes
--- a/bin/android-daily-changes
+++ b/bin/android-daily-changes
@@ -7,27 +7,64 @@ ANDROID_DIR=$(readlink -f $(lookup_file .repo/..))
 CHANGES_DIR=$(dirname $ANDROID_DIR)/$(basename $ANDROID_DIR)-out/daily-changes
 TODAYS_CHANGES_DIR=$CHANGES_DIR/$(today)
 
-how_long='1 day'
-if test $# -gt 0; then
-    how_long=$1
-    TODAYS_CHANGES_DIR=$CHANGES_DIR/$(now)-$(echo $how_long|perl -npe 's,\W,-,g')
+from=
+to=
+TODAYS_CHANGES_DIR=
+ADD_GIT_ARGS=
+
+TEMP=$(getopt -o f:t:d:a: --long from:,to:,dir:,add: -n $(basename $0) -- "$@")
+eval set -- "$TEMP"
+
+while true; do
+    case "$1" in
+	-f|--from)
+	from=$2
+	shift 2
+	;;
+        -t|--to)
+            to=$2
+            shift 2
+            ;;
+        -d|--dir)
+            TODAYS_CHANGES_DIR=$(wlp $2)
+            shift 2
+            ;;
+        -a|--add)
+            ADD_GIT_ARGS=$2
+            shift 2
+            ;;
+	--)
+	shift
+	break
+	;;
+	*)
+	die "internal error"
+	;;
+    esac
+done
+
+export ADD_GIT_ARGS
+
+if test -z "$from"; then
+    from=$(day-start -1)
 fi
 
-since_when=$(now -d "$how_long ago")
-
-if test $# -gt 1; then
-    TODAYS_CHANGES_DIR=$(wlp $2)
+if test -z "$to"; then
+    to=$(day-end -1)
 fi
 
-if test $# -gt 2; then
-    die "Error: Usage $(basename $0) [how_long] [save_log_dir]"
+if test -z "$TODAYS_CHANGES_DIR"; then 
+    if test "$from" = "$(day-start -1)" -a "$to" = "$(day-end -1)"; then
+        TODAYS_CHANGES_DIR=$CHANGES_DIR/$(today -1)
+    else
+        TODAYS_CHANGES_DIR=$CHANGES_DIR/"$from~$to"
+    fi
 fi
 
-mkdir -p $TODAYS_CHANGES_DIR
+mkdir -p "$TODAYS_CHANGES_DIR"
 
-if test $# = 0; then
-    rm -f $CHANGES_DIR/today
-    relative-link $TODAYS_CHANGES_DIR $CHANGES_DIR/today || true
+if test "$from" = "$(day-start -1)" -a "$to" = "$(day-end -1)"; then
+    relative-link "$TODAYS_CHANGES_DIR" $CHANGES_DIR/yesterday || true
 fi
 
 relative-link $CHANGES_DIR $ANDROID_DIR || true
@@ -37,18 +74,18 @@ export ANDROID_DIR TODAYS_CHANGES_DIR
 for x in $(xmlstarlet sel -B -t -m //project -v @path -n -b  $(lookup_file .repo/manifest.xml 2>/dev/null || echo /dev/null)  2>/dev/null); do
     test -d "$x" && continue
     repo sync $(echo $x|perl -npe 's,/+$,,')
-    touch ~/etc/generate-repo-info.mk
+    rm -f .repo/repo_info.pl
 done
 
 my-rfa -j 5 -- '
 #{%sh%}
-log=$TODAYS_CHANGES_DIR/$(repo-path | sed -e "s,/,.,g").git-log;
+log="$TODAYS_CHANGES_DIR"/$(repo-path | sed -e "s,/,.,g").git-log;
 remote=$(repo-remote)
 refname=$(repo-refname)
-git log --format=fuller --since='"$since_when"' $remote/$refname > $log 2>&1
-if test $(stat -c %s $log) = 0;
+git log --format=fuller $ADD_GIT_ARGS --since='"$from"' --until='"$to"' $remote/$refname > "$log" 2>&1
+if test $(stat -c %s "$log") = 0;
 then
-    rm $log
+    rm "$log"
 fi
 #{%/sh%}
 '
