Move some scripts back.
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/android-do-phone-ota b/bin/android-do-phone-ota
--- a/bin/android-do-phone-ota
+++ b/bin/android-do-phone-ota
@@ -1,1 +1,134 @@
-../../src/github/private-config/bin/android-do-phone-ota
+#!/bin/bash
+set -e
+if test -z "$ANDROID_SERIAL"; then
+    export ANDROID_SERIAL=$(my-adb devices?|pn 1)
+fi
+
+export FORWARD_PORT=$(perl -e 'print 54321 + '0x$(echo $ANDROID_SERIAL | md5sum | cut -b 1-3))
+
+if echo $SHELLOPTS | grep xtrace; then
+    export SHELLOPTS
+fi
+
+android_dir=${android_dir:-~/src/android}
+if test ! -e $android_dir/build/envsetup.sh; then
+    echo "Can't find android source repo at ~/src/android."
+    read -e -p "Please input your android source code directory: " android_dir
+    android_dir=${android_dir/\~/$HOME}
+fi
+
+function die() {
+    echo Error: "$@"
+    exit -1
+}
+
+if test ! -e $android_dir/build/envsetup.sh; then
+    die "Can't find android source repo at '$android_dir'"
+fi
+
+export android_dir
+
+if ! running-as-root; then
+    (
+        flock 9
+        cd $android_dir/build/tools/releasetools
+        git fetch smartisan sandbox-for-linux-ota
+        git co FETCH_HEAD
+        sudo modprobe loop >/dev/null 2>&1 || true
+    ) 9> /tmp/$(basename $0).patch.lock
+fi
+
+## start generated code
+TEMP=$(getopt -o fhDd:t:s:b: --long "help,debug,cmReleaseDir:tmpTag:"  -n $(basename $0) -- "$@")
+cmReleaseDir=.
+tmpTag=$$
+export ANDROID_SYSTEM_IMG=
+export ANDROID_BOOT_IMG=
+debug=false
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+        -h|--help)
+            cat <<EOF
+Usage:
+    android-do-phone-ota [-f] [-h|--help] [-D|--debug] [-d|--cmReleaseDir cm-release-dir] [-t|--tmpTag] [-s system_img] [-b boot_img]
+
+        -f: full system, do not compare with phone
+        -h: help
+        -D: enable debugging
+        -d: use the cm release dir specified, or the current dir by default
+        -t: use a tmp tag, mainly for debugging
+        -s: do not use cm released system.img, but use a self built sparse system.img
+        -b: do not use cm released boot.img, but use a self built sparse boot.img
+EOF
+            exit
+            ;;
+        -f)
+            export FULL_SYSTEM_OTA=true
+            shift
+            ;;
+        -D|--debug)
+            debug=true
+            set -x
+            shift
+            ;;
+        -s)
+            ANDROID_SYSTEM_IMG=$2
+            shift 2
+            ;;
+        -b)
+            ANDROID_BOOT_IMG=$2
+            shift 2
+            ;;
+        -d|--cmReleaseDir)
+            cmReleaseDir=$2
+            shift 2
+            ;;
+        -t|--tmpTag)
+            tmpTag=$2
+            shift 2
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
+## end generated code
+if test ! -d "$cmReleaseDir"/sparse_images; then
+    die "Can't open sparse_images from cm release"
+fi
+cmReleaseDir=$(readlink -f $cmReleaseDir)
+
+android-generate-ota-from-cm-release -d "$cmReleaseDir" -t $tmpTag
+cd ~/tmp/system-$tmpTag
+rm push-done -f
+(
+    set -ex
+    my-adb push ota.zip /sdcard/
+    if test "$USER" = bhj -a -e ~/.android/adbkey.pub && ! my-adb cat /data/misc/adb/adb_keys | grep "$(cat ~/.android/adbkey.pub)"; then
+        my-adb 'if test ! -d /data/misc/adb; then mkdir /data/misc/adb; chown system.shell /data/misc/adb; chmod 2750 /data/misc/adb; fi'
+        adb push ~/.android/adbkey.pub /data/misc/adb/adb_keys
+    fi
+    adb forward tcp:$FORWARD_PORT localreserved:scitd
+    my-adb bash -x stcmd-subcase.sh reboot-rom
+    echo srem-helper reboot-rom | nc localhost $FORWARD_PORT
+    touch push-done
+)&
+sudo umount system
+if test $debug = true; then
+    bash || true
+else
+    set -x
+    sleep 5
+    my-adb echo hello
+    wait || true
+    test -e push-done || yes-or-no-p "push-done not found, continue to rm system-$tmpTag?"
+    cd ../
+    rm system-$tmpTag -rf
+    rm system-$tmpTag.img -f
+fi
diff --git a/bin/android-generate-ota-from-cm-release b/bin/android-generate-ota-from-cm-release
--- a/bin/android-generate-ota-from-cm-release
+++ b/bin/android-generate-ota-from-cm-release
@@ -1,1 +1,209 @@
-../../src/github/private-config/bin/android-generate-ota-from-cm-release
+#!/bin/bash
+set -e
+function die() {
+    echo Error: "$@"
+    exit -1
+}
+
+function sudo() {
+    sudo.if "$@"
+}
+
+export android_dir=${android_dir:-~/src/android}
+
+(
+    flock 9
+    cd $android_dir
+    if test ! -e out/host/linux-x86/framework/signapk.jar -o ! -e out/host/linux-x86/bin/imgdiff  -o ! -e out/host/linux-x86/bin/fs_config; then
+        . build/envsetup.sh
+        lunch msm8974sfo_lte-user
+        if test -x ~/external/bin/Linux/ext/ndk/prebuilt/linux-x86/bin/make; then
+            export PATH=~/external/bin/Linux/ext/ndk/prebuilt/linux-x86/bin:$PATH
+        fi
+        if test -x ~/external/bin/Linux/ext/jdk/bin/java; then
+            export PATH=~/external/bin/Linux/ext/jdk/bin:$PATH
+        fi
+        make -j8 signapk imgdiff fs_config;
+    fi
+) 9> /tmp/$(basename $0).build.lock
+
+
+mypath=$(dirname $(readlink -f "$0"))
+## start generated code
+TEMP=$(getopt -o fd:t: --long "fullSystem,cmReleaseDir:tmpPostfix"  -n $(basename $0) -- "$@")
+cmReleaseDir=.
+fullSystem=${FULL_SYSTEM_OTA:-false}
+export tmpPostfix=$$
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+        -d|--cmReleaseDir)
+            cmReleaseDir=$2
+            shift 2
+            ;;
+        -t|--tmpPostfix)
+            tmpPostfix=$2
+            shift 2
+            ;;
+        -f|--fullSystem)
+            fullSystem=true
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
+## end generated code
+if test ! -d "$cmReleaseDir"/sparse_images; then
+    die "Can't open sparse_images from cm release"
+fi
+cmReleaseDir=$(readlink -f "$cmReleaseDir")
+
+(
+    # my-adb 'cd /; set -ex; rm -f /data/phone.md5; find ./system/ -type f | xargs md5sum > /data/system-files.md5.$$ && mv /data/system-files.md5.$$ /data/phone.md5; echo yes'.$$ | grep yes.$$&
+    if test $fullSystem != true; then
+        my-adb rm -f /sdcard/phone.md5
+        (
+            adb forward tcp:$FORWARD_PORT localreserved:scitd
+            echo srem-helper get-system-md5s | nc localhost $FORWARD_PORT
+        )&
+        my-adb bash -x stcmd-subcase.sh get-system-md5s&
+    fi
+    cd "$cmReleaseDir"/sparse_images;
+    if test ! -e ~/tmp/system-$tmpPostfix.img; then
+        if test -e "$ANDROID_SYSTEM_IMG"; then
+            if test "$ANDROID_SYSTEM_IMG" = /dev/zero -o "$ANDROID_SYSTEM_IMG" = /dev/null; then
+                dd if=/dev/zero of=~/tmp/system-$tmpPostfix.img.2 bs=1024 count=1 seek=$(pretty 1024*1024|pn 2)
+                mkfs.ext4 ~/tmp/system-$tmpPostfix.img.2
+            else
+                simg2img "$ANDROID_SYSTEM_IMG" ~/tmp/system-$tmpPostfix.img.2;
+            fi
+        else
+            sparse-unsparse.xml -p system -o ~/tmp/system-$tmpPostfix.img.2
+        fi
+        mv ~/tmp/system-$tmpPostfix.img.2 ~/tmp/system-$tmpPostfix.img
+    fi
+    mkdir -p ~/tmp/system-$tmpPostfix/system
+    cd ~/tmp/system-$tmpPostfix
+    sudo umount system >/dev/null 2>&1 || true
+    sudo umount SYSTEM >/dev/null 2>&1 || true
+    sudo mount -o loop ../system-$tmpPostfix.img system
+    sudo chown $USER\. -R system
+    if test ! -e system/etc/stcmd-scripts/reboot-rom -o ! -e system/etc/stcmd-scripts/get-system-md5s; then
+        mkdir -p system/etc/stcmd-scripts/
+        cp $android_dir/vendor/smartisanhw/log-crawler/scripts/reboot-rom system/etc/stcmd-scripts/
+        cp $android_dir/vendor/smartisanhw/log-crawler/scripts/get-system-md5s system/etc/stcmd-scripts/
+        if test ! -e system/build.prop; then
+            adb pull /system/build.prop system/build.prop
+        fi
+    fi
+    cp $mypath/gapps-system/* system/ -av
+    find system -type f -o -type l > system.list
+    find system -type d |perl -npe 's!$!/!' >> system.list
+
+    find ./system -type f |grep -v system/build.prop | xargs md5sum > cm.md5
+
+    if test $fullSystem != true; then
+        for x in $(seq 1 20); do
+            if my-adb pull /sdcard/phone.md5; then
+                break
+            fi
+            echo wait for phone md5 $x
+            sleep 1
+        done
+        if test ! -e phone.md5; then
+            echo -n > phone.md5
+        fi
+    else
+        echo -n > phone.md5
+    fi
+
+    perl -e 'open($phone, "<", "phone.md5");
+             open($cm, "<", "cm.md5");
+             while (<$phone>) {
+                 chomp;
+                 ($md5, $file) = split(" ");
+                 $phone{$file} = $md5;
+             }
+             while (<$cm>) {
+                 chomp;
+                 ($md5, $file) = split(" ");
+                 $cm{$file} = $md5;
+             }
+             for (keys %cm) {
+                 if ($cm{$_} eq $phone{$_}) {
+                     print "rm -f $_\n";
+                 }
+             }
+             for (keys %phone) {
+                 if ($cm{$_} ne $phone{$_}) {
+                     print "rm-phone $_\n";
+                 }
+             }
+         ' > rm-same-files.sh
+    perl -ne 'print if m/^rm-phone/' rm-same-files.sh > rm-phone.sh
+    perl -ne 'print unless m/^rm-phone/' -i rm-same-files.sh
+    bash rm-same-files.sh
+    rm -rf SYSTEM
+    cp system SYSTEM -av
+    rm -rf RECOVERY BOOT BOOTABLE_IMAGES
+    mkdir -p RECOVERY BOOT BOOTABLE_IMAGES
+    for type in boot recovery; do
+        (
+            TYPE=$(uc $type)
+            cd $TYPE
+            cp "$cmReleaseDir"/$type.img .
+            cp "$cmReleaseDir"/$type.img ../BOOTABLE_IMAGES
+            unbootimg $type.img
+            ramdisk_len2dir ramdisk.img
+            rm ramdisk.img
+            mv ramdisk.img-tmp RAMDISK
+            mv kernel.img kernel
+            echo $PWD/dt.img > dt_args
+            perl -ne "if (m/--base (\S+)/) {print \$1}" mkbootimg.sh > base
+            perl -ne "if (m/--cmdline '(.*?)'/) {print \$1}" mkbootimg.sh > cmdline
+            perl -ne "if (m/--pagesize (\d+)/) {print \$1}" mkbootimg.sh > pagesize
+            echo 0x02000000 > ramdisk_offset
+            echo 0x01E00000 > tags_offset
+        )
+    done
+    cp $mypath/ota/* ./ -av
+    find SYSTEM -type f -name '*.apk' |xargs bash -c 'for apk in "$@"; do
+cat <<EOF
+name="$apk" certificate="PRESIGNED" private_key=""
+EOF
+    done' true > META/apkcerts.txt
+    perl -npe 's/~/$ENV{HOME}/g; s/\$PWD/$ENV{PWD}/g' -i META/misc_info.txt
+
+    for x in alterable.bin emmc_appsboot.mbn NON-HLOS.bin rpm.mbn sbl1.mbn sdi.mbn splash.img tz.mbn udisk.bin; do
+        cp "$cmReleaseDir"/$x RADIO
+    done
+    mv RADIO/splash.img RADIO/splash.bin
+
+    mkdir -p DATA
+    if test $fullSystem != true -o -e ~/src/github/private-config/etc/adbd; then
+        (
+            cd BOOTABLE_IMAGES
+            if test -e "$ANDROID_BOOT_IMG"; then
+                cp "$ANDROID_BOOT_IMG" .
+            fi
+            replace-bootimage -b boot.img -- -d
+        )
+    fi
+
+    zip -qry ota-files.zip BOOT BOOTABLE_IMAGES DATA META OTA RADIO RECOVERY SYSTEM
+    sort system.list | $android_dir/out/host/linux-x86/bin/fs_config -C -S BOOT/RAMDISK/file_contexts > META/filesystem_config.txt
+    zipinfo -1 ota-files.zip | awk 'BEGIN { FS="BOOT/RAMDISK/" } /^BOOT\/RAMDISK\// {print $2}' | $android_dir/out/host/linux-x86/bin/fs_config -C -S BOOT/RAMDISK/file_contexts > META/boot_filesystem_config.txt
+    zipinfo -1 ota-files.zip | awk 'BEGIN { FS="RECOVERY/RAMDISK/" } /^RECOVERY\/RAMDISK\// {print $2}' | $android_dir/out/host/linux-x86/bin/fs_config -C -S BOOT/RAMDISK/file_contexts > META/recovery_filesystem_config.txt
+    zip -q ota-files.zip META/*filesystem_config.txt rm-phone.sh system.list
+    bash -c "
+        set -e
+        cd $android_dir
+        ./build/tools/releasetools/ota_from_target_files -v -p out/host/linux-x86 -d MMC -k vendor/smartisan/security/releasekey -i '' -f 0 $PWD/ota-files.zip $PWD/ota.zip"
+)
