bin/do-capture: allow to force show all items
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/aterr b/bin/aterr
--- a/bin/aterr
+++ b/bin/aterr
@@ -6,15 +6,63 @@ if test "$#" = 0; then
     return
 fi
 
-aterr_args=(
-    "$@"
-)
-function aterr() {
-    ret=$?
-    if test "$ret" != 0; then
-        "${aterr_args[@]}"
-    fi
-    return $?
+function setup-aterr() {
+    ## start code-generator "^\\s *#\\s *"
+    # generate-getopt -P i:ignored-errno=0
+    ## end code-generator
+    ## start generated code
+    TEMP=$(POSIXLY_CORRECT=true getopt -o i:h \
+                          --long ignored-errno:,help \
+                          -n $(basename -- $0) -- "$@")
+    declare ignored_errno=0
+    eval set -- "$TEMP"
+    while true; do
+        case "$1" in
+
+            -i|--ignored-errno)
+                ignored_errno=$2
+                shift 2
+
+                ;;
+            -h|--help)
+                set +x
+                echo -e
+                echo
+                echo Options and arguments:
+                printf %06s '-i, '
+                printf %-24s '--ignored-errno=IGNORED_ERRNO'
+                echo
+                exit
+                shift
+                ;;
+            --)
+                shift
+                break
+                ;;
+            *)
+                die "internal error"
+                ;;
+        esac
+    done
+
+
+    ## end generated code
+
+
+    aterr_args=(
+        "$@"
+    )
+
+    export aterr_ignored_errno=$ignored_errno
+    function aterr() {
+        local aterr_ret=$?
+        if test "$aterr_ret" != 0 -a "$aterr_ret" != "$aterr_ignored_errno"; then
+            ("${aterr_args[@]}") # so that we don't change aterr_ret
+        fi
+        return $aterr_ret
+    }
+
+    trap aterr 0
 }
 
-trap aterr 0
+setup-aterr "$@"
