Add call-home into run every 15 minutes

diff --git a/bin/call-home b/bin/call-home
--- a/bin/call-home
+++ b/bin/call-home
@@ -1,2 +1,14 @@
-#!/bin/bash
-ssh $@ bhj.is-a-geek.org
+#! /bin/bash
+
+(
+    flock -n 9 || { echo 'lock failed at '$(date); exit -1; }
+    while true; do
+	ssh -C2qN -R :$(printf %d 0x2$(from-mac|sha1sum|cut -b 1-3)):localhost:22 bhj.is-a-geek.org -p 443
+	x=30
+	y=$(random 30)
+	((x = x + y))
+	sleep $x
+    done
+    backup-mail
+
+) 9>~/.logs/$(basename $0).lock  2>&1 
