.emacs_d/lisp/ajoke.el: 'C-c f' is now origami .emacs_d/yasnippet/snippets/cc-mode/fe.yasnippet: make it jumpable bin/call-home: call all my homes
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/call-home b/bin/call-home
--- a/bin/call-home
+++ b/bin/call-home
@@ -1,9 +1,9 @@
 #! /bin/bash
 
 . ensure-at-work
-(
-    flock -n 9 || { set +e; echo 'lock failed for home at '$(date); ps-killall sleep.51555005; exit 0; }
-    for home in realhome home; do
+for home in realhome home realhome-pc; do
+    (
+        flock -n 9 || { set +e; echo 'lock failed for home at '$(date); ps-killall sleep.51555005; exit 0; }
         while true; do
             ssh_start_time=$(date +%s)
             remote_bind_port=$(get-about-me remote-bind-port)
@@ -24,7 +24,7 @@
             y=$(random 30)
             ((x = x + y))
             sleep $x.51555005
-        done&
-    done
-) 9>~/.cache/system-config/logs/$(basename $0).lock  2>&1 &
+        done >~/.cache/system-config/logs/call-$home.log 2>&1&
+    ) 9>~/.cache/system-config/logs/$(basename $0).$home.lock  2>&1 &
+done
 
