.emacs_d/lisp/bhj-set-key.el: should be easier to re fontlock lua bin/call-home: fix call-home bin/do-natural-scrolling: fix it for touchpad
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/call-home b/bin/call-home
--- a/bin/call-home
+++ b/bin/call-home
@@ -6,7 +6,7 @@ if test "$USER" != bhj; then
 fi
 
 (
-    flock -n 9 || { echo 'lock failed for home at '$(date); ps-killall sleep.51555005.sleep exit 0; }
+    flock -n 9 || { set +e; echo 'lock failed for home at '$(date); ps-killall sleep.51555005.sleep; exit 0; }
     for home in home realhome; do
         while true; do
             if test $home = home; then
