.bash_completion.d/git-ci: do review in smartcm .sawfishrc: add same author support bin/bbs-robot.exp: use ssh1 bin/bhj-notify: exit early bin/call-home: should not do ssh proxy bin/douban: add loop same author support bin/draw-notification-with-sawfish: fix exit early bin/gerrit-do-review: should not do tracking if set in env bin/gerrit-fix-hooks: fix commit-msg a dead symlink bin/gerrit-pull-config: pull the project's config bin/gerrit-pull-config: push the gerrit config bin/gpt-part-parser.pl: add option to print userdata size bin/random-music-player: add same author support
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/call-home b/bin/call-home
--- a/bin/call-home
+++ b/bin/call-home
@@ -6,25 +6,17 @@ if test "$USER" != bhj; then
 fi
 
 (
-    flock -n 9 || { set +e; echo 'lock failed for home at '$(date); ps-killall sleep.51555005.sleep; exit 0; }
+    flock -n 9 || { set +e; echo 'lock failed for home at '$(date); ps-killall sleep.51555005; exit 0; }
+    sudo systemctl status ssh.service|grep -e 'active .running' || sudo systemctl restart ssh.service
     for home in home realhome; do
         while true; do
-            if test $home = home; then
-                C=C;
-            else
-                C=
-            fi
-            sudo systemctl status ssh.service|grep -e 'active .running' || sudo systemctl restart ssh.service
             ssh_start_time=$(date +%s)
             remote_bind_port=$(get-about-me remote-bind-port)
             if test "$remote_bind_port" = unknown; then
                 remote_bind_port=$(printf %d 0x2$( (from-mac; echo $home)|sha1sum|cut -b 1-3))
             fi
-            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=300 -i ~/.ssh/id_rsa_nopass -${C}2qN $(
-                if test $home = home; then
-                    echo -D 7070
-                fi
-                ) -R :$remote_bind_port:localhost:22 $(if test -e ~/.config/system-config/call-home-user -a $home = home; then cat ~/.config/system-config/call-home-user; fi)$home
+            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=300 -i ~/.ssh/id_rsa_nopass -qN \
+                -R :$remote_bind_port:localhost:22 $(if test -e ~/.config/system-config/call-home-user -a $home = home; then cat ~/.config/system-config/call-home-user; fi)$home
             if test $? = 137; then
                 continue
             fi
