Fix the func call for macros

diff --git a/bin/call-home b/bin/call-home
--- a/bin/call-home
+++ b/bin/call-home
@@ -10,12 +10,17 @@ if test "$USER" != bhj; then
 fi
 
 (
-    flock -n 9 || { echo 'lock failed at '$(date); exit 0; }
+    flock -n 9 || { echo 'lock failed for home at '$(date); exit 0; }
     while true; do
         if test -e ~/.at-home; then
             exit 0
         fi
-	ssh -C2qN -D 18080 -R :$(printf %d 0x2$(from-mac|sha1sum|cut -b 1-3)):localhost:22 bhj.is-a-geek.org -p 443
+	ssh -C2qN -D 18080 -R :$(printf %d 0x2$(from-mac|sha1sum|cut -b 1-3)):localhost:22 bhj.is-a-geek.org -p 443 ||
+        if route -n |grep -e "$(host bhj.is-a-geek.org | pn 4)"; then
+            true
+        else
+            sudo su - -c 'nmcli con down id vpn-home'
+        fi
 	x=30
 	y=$(random 30)
 	((x = x + y))
@@ -24,7 +29,7 @@ fi
 ) 9>~/.logs/$(basename $0).lock  2>&1 &
 
 (
-    flock -n 9 || { echo 'lock failed at '$(date); exit 0; }
+    flock -n 9 || { echo 'lock failed for fixnet at '$(date); exit 0; }
     if test -e ~/.at-home; then
         exit 0
     fi
