bin/call-home: make killing the sleep easier
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/call-home b/bin/call-home
--- a/bin/call-home
+++ b/bin/call-home
@@ -6,7 +6,7 @@ if test "$USER" != bhj; then
 fi
 
 (
-    flock -n 9 || { echo 'lock failed for home at '$(date); exit 0; }
+    flock -n 9 || { echo 'lock failed for home at '$(date); ps-killall sleep.51555005.sleep exit 0; }
     for home in home realhome; do
         while true; do
             if test $home = home; then
@@ -36,7 +36,7 @@ fi
             x=30
             y=$(random 30)
             ((x = x + y))
-            sleep $x
+            sleep $x.51555005
             done&
     done
 ) 9>~/.cache/system-config/logs/$(basename $0).lock  2>&1 &
