../src/github/private-config/bin/search-google: can search baidu baike bin/cc-get-include: fix cc-get-include bin/mailx: fix attachment bin/overide/my-adb: add debug output bin/wine-env: (cd ~/tmp/test-qdir/; wine-env mingw32-make.exe)
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/cc-get-include b/bin/cc-get-include
--- a/bin/cc-get-include
+++ b/bin/cc-get-include
@@ -1,6 +1,16 @@
 #!/bin/bash
+function die() {
+    echo Error: "$@"
+    exit -1
+}
+
 (
+    set -e
     cd $(lookup-file -e .git/..)
+    if test ! -d .git; then
+        die "Can't find .git"
+    fi
+
     find . -iname '*.h*'
     cd /usr/include/
     find . \( -type f -o -type l \) -print
