bin/android-rsync-phone-ota: should not skip media/app when no-hack bin/cp-with-dir-struct: add script to copy symlinks as files
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/cp-with-dir-struct b/bin/cp-with-dir-struct
--- a/bin/cp-with-dir-struct
+++ b/bin/cp-with-dir-struct
@@ -1,11 +1,24 @@
 #!/bin/bash
 target_dir=$1
 shift
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
 for x in "$@"; do
     mkdir -p "$target_dir/$(dirname "$x")"
-    if test $(basename $0) = mv-with-dir-struct; then
+    if test $b0 = mv-with-dir-struct; then
         mv "$x" "$target_dir/$(dirname "$x")" -v -n
-    else
+    elif test $b0 = cp-with-dir-struct; then
         cp "$x" "$target_dir/$(dirname "$x")" -av
+    elif test $b0 = cp-with-dir-struct-L; then
+        cp "$x" "$target_dir/$(dirname "$x")" -rv -H
+    else
+        die "don't know how to do $0"
     fi
 done
