Do full fastboot including.

diff --git a/bin/do-fastboot-full b/bin/do-fastboot-full
--- a/bin/do-fastboot-full
+++ b/bin/do-fastboot-full
@@ -23,6 +23,17 @@
 
 set -e
 cd $(lookup_file flashing)
+function die() {
+    echo "$@"
+    exit -1
+}
+
+if test $# != 1 -o ! -e $1; then
+    die "Usage: $(basename $0) XXX.blf"
+fi
+
+
+export blf=$1
 
 function do-partition() {
     fastboot erase $1;
@@ -32,39 +43,74 @@ function do-partition() {
     fastboot flash $1 ${2:-$1.img}
 }
 
+function get-image-path() {
+    get-blf-img-val $blf $1 Path
+}
+
+generate-ntim.pl $blf || die 'generate ntim failed, must stop!'
+
+# $for x in $(seq 1 16); do echo $(get-blf-img-val *.blf $x 'ID Name') $(get-blf-img-val *.blf $x Path);  done
+# TIMH PXA920_NTIM.bin
+# OBMI TTC2_Sultan_Loader_3_2_13_LINUX.bin
+# PXAY pxafs.img
+# USRY userdata.img
+# SYSY system.img
+# RCOV ramdisk-recovery.img
+# MNTN uImage-mt
+# ZIMG uImage
+# RAMD ramdisk.img
+# GRBI TTC1_M05_AI_A1_Flash.bin
+# ARBI Arbel_DIGRF3.bin
+# OSLO u-boot.bin
+# RBLI ReliableData.bin
+# PLGO logo.bin
+# PMCE prdcfg.bin
+# ERAN panic.part
 
 # tim               =                                       , start:        0B, size:      256K, end:        0B
+fastboot erase tim # we will erase it first (in case there is BBM, bad block
+		   # management), but flash it last (in case something went
+		   # wrong, the ROM will notice the empty tim and enter flash
+		   # mode for Software Downloader).
+#
 # obm               =                                       , start:      256K, size:      256K, end:        0B
+do-partition obm "$(get-image-path OBMI)"
 # uboot             =                                       , start:      512K, size:      512K, end:        0B
+do-partition uboot "$(get-image-path OSLO)"
 # ramdisk           =                                       , start:        1M, size:      256K, end:        0B
-do-partition ramdisk
+do-partition ramdisk "$(get-image-path RAMD)"
 # imei              =                                       , start:    1M256K, size:      256K, end:        0B
 # arbelbinary       =                                       , start:    1M512K, size:        7M, end:        0B
-do-partition arbelbinary Arbel_DIGRF3.bin
+do-partition arbelbinary "$(get-image-path ARBI)"
 # msabinary         =                                       , start:    8M512K, size:        1M, end:        0B
-do-partition msabinary TTC1_M05_AI_A1_Flash.bin
+do-partition msabinary "$(get-image-path GRBI)"
 # kernel            =                                       , start:    9M512K, size:        4M, end:        0B
-do-partition kernel uImage
+do-partition kernel "$(get-image-path ZIMG)"
 # maintenance       =                                       , start:   13M512K, size:        4M, end:        0B
-do-partition maintenance uImage-mt
+do-partition maintenance "$(get-image-path MNTN)"
 # recovery          =                                       , start:   17M512K, size:        5M, end:        0B
-do-partition recovery ramdisk-recovery.img
+do-partition recovery "$(get-image-path RCOV)"
 # misc              =                                       , start:   22M512K, size:      256K, end:        0B
 fastboot erase misc
 # cache             =                                       , start:   22M768K, size:   81M256K, end:        0B
 fastboot erase cache
 # system            =                                       , start:      104M, size:      160M, end:        0B
-do-partition system
+do-partition system "$(get-image-path SYSY)"
 # userdata          =                                       , start:      264M, size:      216M, end:        0B
-do-partition userdata
+do-partition userdata "$(get-image-path USRY)"
 # logo              =                                       , start:      480M, size:    3M256K, end:        0B
-do-partition logo logo.bin
+do-partition logo "$(get-image-path PLGO)"
 # env               =                                       , start:  483M256K, size:      512K, end:        0B
 # kpanic            =                                       , start:  483M768K, size:      256K, end:        0B
 # nvm               =                                       , start:      484M, size:        8M, end:        0B
 fastboot erase nvm
 # telephony         =                                       , start:      492M, size:        8M, end:        0B
-do-partition telephony pxafs.img
+do-partition telephony "$(get-image-path PXAY)"
 # reserved          =                                       , start:      500M, size:       12M, end:        0B
+
+
+# flash tim
+fastboot flash tim "$(get-image-path TIMH)".out
+
 read -p "Press enter to restart fastboot "
 fastboot reboot
