bin/edit: allow to use with jump server
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/emacs-current-file b/bin/emacs-current-file
--- a/bin/emacs-current-file
+++ b/bin/emacs-current-file
@@ -1,15 +1,55 @@
-#!/usr/bin/env exec-with
+#!/bin/bash
 
-exec-with emacsclient -e %s | tr -d '\\'
+set -e
 
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+
+abs0=$0
+if ! [[ $abs0 =~ ^/ ]]; then
+    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
+        abs0=$PWD/$abs0
+    elif test -e "$(which $0)"; then
+        abs0=$(which $0)
+    else
+        die "Can't find abs path for $0"
+    fi
+fi
+
+b0=$(basename $0)
+
+emacsclient -e "$(
+cat <<'EOF16e1379802c6' | . .replace-%%
+; {%emacs-lisp-mode%}
 ;;;;  real script start here
 (let ((buffers (buffer-list))
       buf)
   (while buffers
     (setq buf (car buffers)
           buffers (cdr buffers))
-    (when (buffer-file-name buf)
+    (when (or (and
+               (string= "<%b0%>" "emacs-current-file")
+               (buffer-file-name buf))
+              (and
+               (string= "<%b0%>" "emacs-current-text")
+               (not (string= (buffer-name buf) " *server*"))))
       (setq buffers nil)))
-  (message "current-file %s" (buffer-file-name buf))
-  (intern (buffer-file-name buf)))
+  (message "current-file %s" (buffer-name buf))
+  (or (and
+       (string= "<%b0%>" "emacs-current-file")
+       (intern (buffer-file-name buf)))
+      (and
+       (string= "<%b0%>" "emacs-current-text")
+       (with-current-buffer buf
+         (intern (buffer-substring-no-properties (point-min) (point-max)))))))
+; {%/emacs-lisp-mode%}
+EOF16e1379802c6
+
+)" | tr -d '\\'
 
diff --git a/bin/emacs-quote-string b/bin/emacs-quote-string
--- a/bin/emacs-quote-string
+++ b/bin/emacs-quote-string
@@ -1,2 +1,38 @@
 #!/bin/bash
-echo -n "$1" | perl -npe 's/\\/\\\\/g; s/"/\\"/g'
+
+set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+
+abs0=$0
+if ! [[ $abs0 =~ ^/ ]]; then
+    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
+        abs0=$PWD/$abs0
+    elif test -e "$(which $0)"; then
+        abs0=$(which $0)
+    else
+        die "Can't find abs path for $0"
+    fi
+fi
+
+b0=$(basename $0)
+
+if test "${b0}" = emacs-quote-string; then
+    echo -n "$1" | perl -npe 's/\\/\\\\/g; s/"/\\"/g'
+elif test "${b0}" = lua-quote-string; then
+    n_equals=
+    while true; do
+        if ! echo "${1}" | grep -q -e "\[${n_equals}\["; then
+            echo "[${n_equals}[$1]${n_equals}]";
+            exit
+        fi
+        n_equals="${n_equals}="
+    done
+fi
