bin/emacs-get-android-clipboard: use unicode
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/emacs-get-android-clipboard b/bin/emacs-get-android-clipboard
--- a/bin/emacs-get-android-clipboard
+++ b/bin/emacs-get-android-clipboard
@@ -1,5 +1,51 @@
 #!/bin/bash
 set -x
+set -e
+## start code-generator "^\\s *#\\s *"
+# generate-getopt -P uextract-url
+## end code-generator
+## start generated code
+TEMP=$(POSIXLY_CORRECT=true getopt -o uh \
+                      --long extract-url,help,no-extract-url \
+                      -n $(basename -- $0) -- "$@")
+declare extract_url=false
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+
+        -u|--extract-url|--no-extract-url)
+            if test "$1" = --no-extract-url; then
+                extract_url=false
+            else
+                extract_url=true
+            fi
+            shift
+
+            ;;
+        -h|--help)
+            set +x
+            echo -e
+            echo
+            echo Options and arguments:
+            printf %06s '-u, '
+            printf %-24s '--[no-]extract-url'
+            echo
+            exit
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error: $(. bt; echo; bt | indent-stdin)"
+            ;;
+    esac
+done
+
+
+## end generated code
+
 exec 2>~/tmp/emacs-get-android-clipboard.log
 if test $(basename $0) = emacs-get-android-clipboard; then
     getclip-android|putclip
@@ -7,7 +53,7 @@ else
     putclip "$(getphone-android|perl -npe 's/\+86//')"
 fi
 
-if [[ "$(sawfish-top-window)" =~ Firefox ]]; then
+if test "${extract_url}" = true || [[ "$(sawfish-top-window)" =~ Firefox ]]; then
     old_text=$(getclip)
     urls=$(
         perl -e "$(
@@ -17,8 +63,10 @@ use URI::Find;
 use strict;
 use File::Slurp;
 
-my $text = join(" ", @ARGV);
-my $finder = URI::Find->new( sub { print $_[1] . "\n" } );
+use Encode;
+
+my $text = decode_utf8 join(" ", @ARGV);
+my $finder = URI::Find->new( sub { print encode_utf8 $_[1] . "\n" } );
 $finder->find(\$text );
 # {%/perl-mode%}
 EOF63aa0d87444c
