bin/.gerrit-query-helper: fix jq version
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/fake-jenkins b/bin/fake-jenkins
--- a/bin/fake-jenkins
+++ b/bin/fake-jenkins
@@ -1,5 +1,22 @@
 #!/bin/bash
 
-export JENKINS_SERVER_COOKIE=true
-export HUDSON_COOKIE=true
+set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
+if test "${b0}" = fake-jenkins; then
+    export JENKINS_SERVER_COOKIE=true
+    export HUDSON_COOKIE=true
+elif test "${b0}" = fake-no-jenkins; then
+    export JENKINS_SERVER_COOKIE=
+    export HUDSON_COOKIE=
+fi
+
 "$@"
