bin/firefox: bring firefox to top
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/firefox b/bin/firefox
--- a/bin/firefox
+++ b/bin/firefox
@@ -1,1 +1,16 @@
-../../external/firefox/firefox
+#!/bin/bash
+
+if test -e ~/external/the-firefox; then
+    the_firefox=$(readlink -f ~/external/the-firefox)
+elif test -e ~/system-config/bin/the-firefox; then
+    the_firefox=$(readlink -f ~/system-config/bin/the-firefox)
+elif test -x /usr/bin/firefox; then
+    the_firefox=/usr/bin/firefox
+else
+    bhj-notify "Error" "Firefox not found, please install it first!"
+    exit 1
+fi
+
+find-or-exec firefox $the_firefox
+$the_firefox "$@"&
+
