.emacs_d/lisp/ajoke.el: tramp setenv; android add string .emacs_d/lisp/bhj-defines.el: shell-command-on-region does not respect tramp .emacs_d/lisp/bhj-defines.el: bhj-help-it should work with local, not tramp, because we want use firefox .emacs_d/yasnippet/snippets/nxml-mode/view: make view snippet more flexible .git-push-mac-hooks: should warn when syncing my versions of files bin/Linux/config/install-pkgs: should not intsall missing packages sometimes bin/adb-long-press: for android ahk bin/adb-send-weixin: send text in weixin bin/adb-tap: for android ahk bin/android-extract-from-sdk-txt: exec $0 is harmful bin/ep: edit a project file, find using beagrep-glob bin/freemarker: do some error checking bin/git-interactive-add: allow to delete a file bin/overide/adb: should not mount /mnt, android will fail
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/freemarker b/bin/freemarker
--- a/bin/freemarker
+++ b/bin/freemarker
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+set -e
+function die() {
+    echo Error: "$@"
+    exit -1
+}
+
 export PATH=/usr/bin:$PATH
 
 file=~/external/FreeMarker/FreeMarker.class;
@@ -11,6 +17,9 @@ if test ! -e $file -o $file -ot ~/bin/FreeMarker.d/FreeMarker.java; then
         cp ~/bin/FreeMarker.d/* . -av
         javac -cp /usr/share/java/freemarker.jar $(find . -name '*.java')
     )
+fi
+if test ! -e /usr/share/java/xml-apis.jar -o ! -e /usr/share/java/freemarker.jar; then
+    die "can't find freemarker.jar or xml-apis.jar"
 fi
 
 java -cp /usr/share/java/xml-apis.jar:/usr/share/java/freemarker.jar:$(dirname $file) FreeMarker "$@" 2>/dev/null
