bin/get-my-ip: use 1 script for both mac and ip
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/get-my-ip b/bin/get-my-ip
--- a/bin/get-my-ip
+++ b/bin/get-my-ip
@@ -1,16 +1,73 @@
 #!/bin/bash
 
+set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+
+abs0=$0
+if ! [[ $abs0 =~ ^/ ]]; then
+    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
+        abs0=$PWD/$abs0
+    elif test -e "$(which $0)"; then
+        abs0=$(which $0)
+    else
+        die "Can't find abs path for $0"
+    fi
+fi
+
+b0=$(basename $0)
+
 if test $# = 0; then
     net=$(route -n | grep '^\Q0.0.0.0\E' -P|sort -n -k 6|head -n 1 |pn 8)
 else
     net=$1
 fi
 
-ip=$(
-    ifconfig $net |
-        perl -ne 'print "$1\n" if m/(?:inet addr:|^\s*inet\s+)(\d+\S+)/'|
-        grep -v 127.0.0.1)
-echo -n $ip
-if is-tty-io; then
-    putclip "$ip"
+if test "${b0}" = get-mac; then
+    case $(uname) in
+        Darwin|Linux)
+            ifconfig $net | grep -B 1 -P -e '^\s+ether\s+'|perl -ne '
+            # {%perl-mode%}
+            if (m/^p2p\d+:/) {
+                $p2p = 1;
+            } elsif (m/^\w+:/) {
+                $p2p = 0;
+            } elsif (m/^\s+ether\s+([a-f0-9:]{17}\b)/i) {
+                unless ($p2p) {
+                    print $1;
+                    exit 0
+                }
+            }
+            # {%/perl-mode%}
+        '
+            ;;
+        CYGWIN*)
+            ifconfig /all | tr -d '\r' | perl -ne 'if (m/eth\d+:\s*$/)
+            {
+                while (<>) {
+                    if (m/Physical Address.*:\s*(.*)/) {
+                        print lc($1);
+                        exit;
+                    }
+                }
+            }'
+            ;;
+    esac |head -n 1|
+        perl -npe 's/:/-/g; s/\s//g; $_ = lc $_'
+else
+    ip=$(
+        ifconfig $net |
+            perl -ne 'print "$1\n" if m/(?:inet addr:|^\s*inet\s+)(\d+\S+)/'|
+            grep -v 127.0.0.1)
+    echo -n $ip
+    if is-tty-io; then
+        putclip "$ip"
+    fi
 fi
