bin/get-mails: do lock offlineimap to avoid false notification
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/get-mails b/bin/get-mails
--- a/bin/get-mails
+++ b/bin/get-mails
@@ -1,5 +1,18 @@
 #!/bin/bash
 
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
+exec 9> ~/.cache/system-config/logs/$b0.lock
+
+flock 9
+
 if (
     set -e
     version=$(offlineimap --version | perl -npe 's/\.//g')
