.sawfishrc: use the clipboard bin/after-co-ln-s.sh: put it into a separate script bin/android-make: add a verbose option, fix kernel parallel build where ccache env is not set up because I changed HOME bin/ask-to-sync-org: ask to sync the mobile org every day bin/cgi-bin/rem-collect.cgi: add a script to fix rem bin/git-push-mac: add option to not work on submodule bin/is-my-adb-device: add a script to tell if it is my adb device (for starting mobile org sync) bin/is-tty-io: if reading null, then not a tty bin/logcat: do not use root, because logcat -k is not supported anymore bin/mm-ant: add a default tag bin/ramdump.sh: add a script to do qualcomm ramdump bin/remote-edit-secure: add a script for remote editing, where only emacsclient is allowed in .ssh/authorized_keys bin/replug-adb: replug the adb, but can't cause udev to notice it bin/sync-etc-files: sync etc files and start (restart) udev to notice the changes bin/sync-mobile-org: fix sync-mobile-org for new version of MobileOrg bin/watch-and-sync: recursive watch etc/custom.el: fix the mobileorg etc/udev/rules.d/90-bhj-personal.rules: do sync automatically (mobile org) gcode/android-templates/other/BroadcastReceiver/template.xml: fix poorman's android template
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/git-push-mac b/bin/git-push-mac
--- a/bin/git-push-mac
+++ b/bin/git-push-mac
@@ -4,6 +4,25 @@ if test "$DEBUG" = true; then
     set -x
 fi
 
+TEMP=$(getopt -o n --long no-submodule -n $(basename $0) -- "$@")
+no_submodule=
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+        -n|--no-submodule)
+            no_submodule=true
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
 . ~/bin/.gitx
 
 (
@@ -44,6 +63,9 @@ git-interactive-add
 
 
 if output=$(
+        if test "$no_submodule" = true; then
+            exit 1 # not 0!
+        fi
         git submodule foreach 'bash -c "git-push-mac || echo hello $(pwd) failed&"' |
         tee /dev/stderr |
         grep "^hello.*failed$"
@@ -176,13 +198,11 @@ function die() {
     exit -1
 }
 
-branch=$(
-    if test -e ~/system-config/etc/branch-fileters/$(relative-path $PWD ~/system-config).sh; then
-        bash ~/system-config/etc/branch-fileters/$(relative-path $PWD ~/system-config).sh my-master;
-    else
-        echo master
-    fi
-)
+branch=master
+
+if test -e ~/system-config/etc/branch-fileters/$(relative-path $PWD ~/system-config).sh; then
+  branch=$(bash ~/system-config/etc/branch-fileters/$(relative-path $PWD ~/system-config).sh my-master)
+fi
 
 if test "$(git symbolic-ref --short HEAD)" != $branch; then
     if git-is-ancestor $branch HEAD; then
