add help for git-rewrite-msgs
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/git-rewrite-msgs b/bin/git-rewrite-msgs
--- a/bin/git-rewrite-msgs
+++ b/bin/git-rewrite-msgs
@@ -2,8 +2,31 @@
 
 set -e
 
+me=$(readlink -f $BASH_SOURCE)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $BASH_SOURCE)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+
+abs0=$BASH_SOURCE
+if ! [[ $abs0 =~ ^/ ]]; then
+    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
+        abs0=$PWD/$abs0
+    elif test -e "$(which $BASH_SOURCE)"; then
+        abs0=$(which $BASH_SOURCE)
+    else
+        die "Can't find abs path for $BASH_SOURCE"
+    fi
+fi
+
+b0=$(basename $BASH_SOURCE)
+
 ## start code-generator "^\\s *#\\s *"
-# generate-getopt s:start-with=1 '?"start reworking with which commit (in reverse order, 1 means the oldest patch)"'
+    # generate-getopt '?"$b0 OPTIONS REV1 [REV2]"' \
+        # s:start-with=1 '?"start reworking with which commit (in reverse order, 1 means the oldest patch)"'
 ## end code-generator
 ## start generated code
 TEMP=$( getopt -o s:h \
@@ -21,7 +44,7 @@ while true; do
             ;;
         -h|--help)
             set +x
-            echo -e
+            echo -e "$b0 OPTIONS REV1 [REV2]"
             echo
             echo Options and arguments:
             printf %06s '-s, '
