mf

diff --git a/bin/git-mac-branch b/bin/git-mac-branch
--- a/bin/git-mac-branch
+++ b/bin/git-mac-branch
@@ -40,8 +40,8 @@ else
     fi
 fi
 
-GITPUSHMACFORCE=true
-if git submodule foreach 'bash -c "git-push-mac . >/dev/null 2>&1 || echo failed"' | grep failed;
+
+if git submodule foreach 'bash -c "export GITPUSHMACFORCE=true; git-push-mac . >/dev/null 2>&1 || echo failed"' | grep failed;
 then
     exit -1
 else
