bin/git-get: no tags bin/overide/repo: do not send mail for repo
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/git-get b/bin/git-get
--- a/bin/git-get
+++ b/bin/git-get
@@ -86,8 +86,8 @@ if test ! -d $dir/.git; then
     mkdir -p $dir
     (
         cd $dir
-        if ! git clone --single-branch -b $branch $url . $(if test "$reference"; then echo --reference "$reference"; fi) && # --single-branch fails for s:git-repo
-           ! git clone -b $branch $url . $(if test "$reference"; then echo --reference "$reference"; fi); then
+        if ! git clone --no-tags --single-branch -b $branch $url . $(if test "$reference"; then echo --reference "$reference"; fi) && # --single-branch fails for s:git-repo
+           ! git clone --no-tags -b $branch $url . $(if test "$reference"; then echo --reference "$reference"; fi); then
             git init .
             git commit -m 'init commit' --allow-empty --author 'qualcomm <someone@qualcomm.com>'
             git push $url HEAD:refs/heads/$branch
