.sawfishrc: C-z is working again for shell bin/after-co-ln-s.sh: ask less questions bin/android-rsync-phone-ota: use abs path for xml bin/git-remote-url: should handle bare .git bin/my-rfa: should handle all projects, those with same name/path, and omitted bin/oem-get-release-files: add a script to extract minimum oem bin/toggle-rdesktop-keys: be quiet etc/tsocks.conf: make some local
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/git-remote-url b/bin/git-remote-url
--- a/bin/git-remote-url
+++ b/bin/git-remote-url
@@ -4,7 +4,14 @@ set -e
 if test $PWD = $HOME; then
     cd system-config
 fi
-gitd=$(lookup-file -e .git)
+gitd=$(lookup-file -e .git) || true
+if test -z "$gitd"; then
+    if [[ $PWD =~ .*\.git ]]; then
+        gitd=$PWD
+    else
+        die "can't find .git"
+    fi
+fi
 if test -e $gitd/svn/.metadata; then
     url=$(git svn info | grep "^URL:" | pn 2 | head -n 1)
 else
