bin/grep-errors: make it faster
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/grep-errors b/bin/grep-errors
--- a/bin/grep-errors
+++ b/bin/grep-errors
@@ -17,16 +17,58 @@ export LANGUAGE=en_US:en
     done
 fi
 
-pcre=
-if test "$#" = 1 -a -e "$1"; then
-    pat=$(perl -ne 'print if m/defun bhj-occur-make-errors/..m/let.*bhj-occur-regexp/' ~/system-config/.emacs_d/lisp/bhj-defines.el|tail -n 1|perl -npe 's/.*(".*").*/$1/')
-else
-    pat=${1:-'"Error [0-9]+"'}
-    pcre=-P
-    echo pat is $pat
-    shift
-fi
 
+## start code-generator "^\\s *#\\s *"
+# generate-getopt m:max-line-length=1000
+## end code-generator
+## start generated code
+TEMP=$( getopt -o m:h \
+               --long max-line-length:,help \
+               -n $(basename -- $0) -- "$@")
+declare max_line_length=1000
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+
+        -m|--max-line-length)
+            max_line_length=$2
+            shift 2
+
+            ;;
+        -h|--help)
+            set +x
+            echo -e
+            echo
+            echo Options and arguments:
+            printf %06s '-m, '
+            printf %-24s '--max-line-length=MAX_LINE_LENGTH'
+            echo
+            exit
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
+
+## end generated code
+
+pcre=-P
+pat=$(perl -ne 'print if m/defun bhj-occur-make-errors/..m/let.*bhj-occur-regexp/' ~/system-config/.emacs_d/lisp/bhj-defines.el|
+          tail -n 1 |
+          perl -npe 's/.*(".*").*/$1/; s/\\\\\|/|/g; s/(?<!\\)\(/\\(/g'
+   )
+eval pat="${pat}"
+
+if ! test "$#" = 1 -a -e "$1"; then
+    die "Can only run with 1 BUILD.LOG file"
+fi
 
 false_positives=$(
     cat <<'EOF'
@@ -71,5 +113,6 @@ EOF
     fi
 
                )
-echo grep -i -H -n $pcre -e "$pat" "$@" |bash | grep -v "$(echo -n "$false_positives" | rm-last-nl | tr \\n \|)" -P -i
+
+cut -b 1-${max_line_length} "$@" | grep -i -H -n $pcre -e "$pat" --label="$*" | grep -v "$(echo -n "$false_positives" | rm-last-nl | tr \\n \|)" -P -i
 true
