bin/douban: should not check the icon when like music bin/gerrit-use-utf8: added single table support bin/java7: should now use java8 bin/like-mp3-tags: allow to use album picture bin/mm: should not change the makefile bin/repo-cherry-find-all: should allow to ask for args when in git repos bin/update-android-mirror: update all major -dev branches
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/java7 b/bin/java7
--- a/bin/java7
+++ b/bin/java7
@@ -1,9 +1,22 @@
 #!/bin/bash
 
-if test $(basename $0) = java7; then
-    PATH=/usr/lib/jvm/java-7-openjdk-amd64/bin:$PATH
-else # java6
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
+
+number=${b0#java}
+if test -e /usr/lib/jvm/java-$number-openjdk-amd64/bin; then
+    PATH=/usr/lib/jvm/java-$number-openjdk-amd64/bin:$PATH
+elif test "$number" = 6; then
     PATH=~/external/bin/Linux/ext/jdk/bin:$PATH
+else
+    die "Can't find the java binary for $number at /usr/lib/jvm/java-$number-openjdk-amd64/bin"
 fi
 if test $# = 0; then
     start_recursive_shell $(basename $0)
