.emacs_d/yasnippet/snippets/sh-mode/me: Fix me, should use BASH_SOURCE bin/screen-lock-off: make sure to reset keyboard
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/jc-create-or-update b/bin/jc-create-or-update
--- a/bin/jc-create-or-update
+++ b/bin/jc-create-or-update
@@ -2,6 +2,33 @@
 
 set -e
 
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+
+abs0=$0
+if ! [[ $abs0 =~ ^/ ]]; then
+    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
+        abs0=$PWD/$abs0
+    elif test -e "$(which $0)"; then
+        abs0=$(which $0)
+    else
+        die "Can't find abs path for $0"
+    fi
+fi
+
+b0=$(basename $0)
+
+if test "${EMACS}" -a $# = 0; then
+    nohup setsid bash -c 'set -x; xml=$(emacs-current-file); out-of-emacs bash -x '${b0}' ${xml%.xml} < ${xml}' true </dev/null > ~/tmp/$b0.log 2>&1&
+    exit
+fi
+
 
 ## start code-generator "^\\s *#\\s *"
 # generate-getopt j:jenkins-server
