bin/do-flashing: fix exe rename caused fail to kill bin/gerrit-push-review: do review after confirm bin/logout-by-killing: should use uid for matching bin/repo-cherry-find-all: use xml by default bin/repo-cherry-pick-all: use perl regexp
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/logout-by-killing b/bin/logout-by-killing
--- a/bin/logout-by-killing
+++ b/bin/logout-by-killing
@@ -4,7 +4,12 @@
 if id | grep 'uid=0\b' -P; then
     umount -l ~/smb;
     screen_pid=$(ps.pl SCREEN.first|grep SCREEN|pn 1)
-    ps -eo user,pid | grep "^${OLDUSER:-bhj}\s+" -P | pn 2 |
+    uid=$(id ${OLDUSER:-bhj} | perl -npe 's,^uid=(\d+).*,$1,')
+    if ! [[ $uid =~ ^[0-9]+$ ]]; then
+        echo "Can't determine your uid: $uid"
+        exit 1
+    fi
+    ps -eo uid,pid | grep "^\s*$uid\s+" -P | pn 2 |
         while read pid; do
             if test "$pid" = "$screen_pid"; then
                 continue
