bin/cowbuilder-bhj: fix link error for ww bin/daily-build-ww: fix .spec file error, add rpm build bin/mach-bhj: ww rpm build ok for fedora
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/mach-bhj b/bin/mach-bhj
--- a/bin/mach-bhj
+++ b/bin/mach-bhj
@@ -1,12 +1,36 @@
 #!/bin/bash
 
 umask 002
-mach yum install autoconf bison gdb gettext git-svn libnotify-devel libuuid-devel libXext-devel ncurses-devel openssl-devel openssl-libs qconf qt4 qt4-devel  qt-devel rsync strace texinfo uuid-c++-devel uuid-devel qtwebkit-devel qjson-devel
+
+root=fedora-development-x86_64-core
+TEMP=$(getopt -o r: --long root: -n $(basename $0) -- "$@")
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+        -r|--root)
+            root=$2
+            shift 2
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
+mach -r $root yum install autoconf bison gdb gettext git-svn libnotify-devel libuuid-devel libXext-devel ncurses-devel openssl-devel openssl-libs qconf qt4 qt4-devel  qt-devel rsync strace texinfo uuid-c++-devel uuid-devel qtwebkit-devel qjson-devel
 
 cd ~/src/github/lww
 git clean -xfd
 rsync AliWangWangLinux_back/* aliwangwang-1.0.0 -av
 cp ./aliwangwang-1.0.0/aliwangwang.spec .
 tar czfv ./aliwangwang-1.0.0.tar.gz aliwangwang-1.0.0
-sudo rm /var/lib/mach/roots/fedora-development-x86_64-core/usr/src/rpm/*/* -rf
-mach build -ba --nodeps -v *.spec
+sudo rm /var/lib/mach/roots/$root/usr/src/rpm/*/* -rf
+sudo mount -t proc proc /var/lib/mach/roots/$root/proc
+sudo rm /var/lib/mach/states/$root/lock -f
+mach -r $root build -ba --nodeps -v *.spec || true
+cd /var/lib/mach/roots/$root/usr/src/rpm/RPMS
+rsync aliwangwang-1*.rpm bhj-win7:/var/www/linux-wangwang/$(today)/ -v
