.emacs: fix org-mode =echo 'hello world'= bin/blog: Fix internal blog bin/get-mails: get all mails bin/maildir-icedove-view: try to debug beagle can't open mail issue bin/of-github-page: should fix blog/../blog bin/org-export-bare.sh: fix doc export after blog export bin/sparse-unsparse.xml: add help info bin/yes-or-no-p: add help doc/galaxy-nexus-root/data/start-debian2.sh: fix m1l memory leak
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/maildir-icedove-view b/bin/maildir-icedove-view
--- a/bin/maildir-icedove-view
+++ b/bin/maildir-icedove-view
@@ -1,6 +1,18 @@
 #!/bin/bash
 
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
+
 if test ! -e "$1"; then
+    echo "$1" > ~/tmp/x.eml
+    bhj-notify $b0 "$1 not exist"
     die "Error: Usage $(basename $0) MAILDIR-EMAIL-FILE"
 fi
 
