bin/adb-push: fix adb-push for chunge bin/mm-adb: do not print too much for adb-push bin/offlineimap-fix-uid-validity: allow force etc/custom.el: remove some old custom keys
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/mm-adb b/bin/mm-adb
--- a/bin/mm-adb
+++ b/bin/mm-adb
@@ -3,6 +3,64 @@
 set -o pipefail
 
 set -e
+
+
+## start code-generator "^\\s *#\\s *"
+# generate-getopt @push-again @list?'list which files are updated in last build'
+## end code-generator
+## start generated code
+TEMP=$(getopt -o h \
+              --long push-again,list,help,no-push-again,no-list \
+              -n $(basename -- $0) -- "$@")
+push_again=false
+list=false
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+
+        --push-again|--no-push-again)
+            if test "$1" = --no-push-again; then
+                push_again=false
+            else
+                push_again=true
+            fi
+            shift
+            ;;
+        --list|--no-list)
+            if test "$1" = --no-list; then
+                list=false
+            else
+                list=true
+            fi
+            shift
+            ;;
+        -h|--help)
+            set +x
+            echo
+            echo
+            echo Options and arguments:
+            printf "%06s" " "
+            printf %-24s '--[no-]list'
+            echo 'list which files are updated in last build'
+            printf "%06s" " "
+            printf %-24s '--[no-]push-again'
+            echo
+            exit
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
+
+## end generated code
+
 repo_dir=$(lookup-file .repo)
 if test -d "$repo_dir"; then
     mark_file=$repo_dir/mm-adb.mark
@@ -10,18 +68,27 @@ else
     die ".repo not found"
 fi
 
-touch $mark_file
-sleep .5
-
-mm "$@"
+if test "$push_again" = true -o "$list" = true; then
+    touch $mark_file
+    sleep .5
+    mm "$@"
+fi
 
 TARGET_OUT=$repo_dir/../$(android-env get_build_var TARGET_OUT)
-find "$TARGET_OUT" -type f -newer $mark_file|while read x; do
-    if test ! -f "$x"; then
-        "$x is not a file, skip"
-        continue
+find "$TARGET_OUT" -type f -newer $mark_file |
+    if test "$list" = true; then
+        cat
+    else
+        while read x; do
+            if test ! -f "$x"; then
+                echo "$x is not a file, skip"
+                continue
+            fi
+            y=$(echo $x|perl -npe 's,.*/target/product/.*?/,/,')
+            printf "adb-push %q %q\n" "$x" "$y"
+            if ! adb-push $x $y </dev/null; then
+                hint "Error: adb push $x $y 失败，请查看原因，然后用 mm-adb --push-again 重新 push。"
+                exit 1
+            fi
+        done
     fi
-    y=$(echo $x|perl -npe 's,.*/target/product/.*?/,/,')
-    printf "adb-push %q %q\n" "$x" "$y"
-    adb-push $x $y >/dev/null 2>&1 </dev/null
-done
