bin/overide/repo: add some info
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/mu-index b/bin/mu-index
--- a/bin/mu-index
+++ b/bin/mu-index
@@ -1,6 +1,50 @@
 #!/bin/bash
+set -e
+
+## start code-generator "^\\s *#\\s *"
+# generate-getopt d:mu-dir='${HOME}/.mu-gtd'
+## end code-generator
+## start generated code
+TEMP=$( getopt -o d:h \
+               --long mu-dir:,help \
+               -n $(basename -- $0) -- "$@")
+declare mu_dir=${HOME}/.mu-gtd
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+
+        -d|--mu-dir)
+            mu_dir=$2
+            shift 2
+
+            ;;
+        -h|--help)
+            set +x
+            echo -e
+            echo
+            echo Options and arguments:
+            printf %06s '-d, '
+            printf %-24s '--mu-dir=MU_DIR'
+            echo
+            exit
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
+
+## end generated code
+
 
 . force-1 || exit 0
 if which mu >/dev/null 2>&1; then
-    mu index --muhome ~/.mu-gtd
+    mu index --muhome ${mu_dir} || true
+    emacsclient -e '(mu4e-update-mail-and-index t)' || true
 fi
