Update my-rfa, which is a parallel 'repo forall'.

diff --git a/bin/my-rfa b/bin/my-rfa
--- a/bin/my-rfa
+++ b/bin/my-rfa
@@ -1,18 +1,21 @@
 #!/bin/bash
 
 set -e
-cd $(lookup_file .repo/..)
-test -d .repo
 
 jobs=1
-TEMP=$(getopt -o j: -n $(basename $0) -- "$@")
+dirs=()
+TEMP=$(getopt -o d:j: -n $(basename $0) -- "$@")
 eval set -- "$TEMP"
 while true; do
     case "$1" in
 	-j)
-	jobs=$2
-	shift 2
-	;;
+	    jobs=$2
+	    shift 2
+	    ;;
+	-d)
+	    dirs=("${dirs[@]}" "$2")
+	    shift 2
+	    ;;
 	--)
 	    shift
 	    break
@@ -23,19 +26,48 @@ while true; do
     esac
 done
 
+if test "${#dirs[@]}" = 0; then
+    dirs=(
+	$(xmlstarlet sel -B -t -m //project -v @path -n $(lookup_file .repo/manifest.xml))
+    )
+else
+    dirs=(
+	$(
+	    for x in "${dirs[@]}"; do
+		if test -d "$x"; then
+		    repo forall "$x" -c 'echo $REPO_PATH'
+		elif test -f "$x"; then
+		    cat "$x"
+		else
+		    die "Error: not a dir: $x"
+		fi
+	    done
+	)
+    )
+fi
 job=0
+
+cd $(lookup_file .repo/..)
+test -d .repo
 
 (cd .repo; make -f ~/etc/generate-repo-info.mk) >/dev/null 2>&1 
 export REPO_INFO=$(readlink -m .repo/repo_info.pl)
 
-for x in $(xmlstarlet sel -B -t -m //project -v @path -n .repo/manifest.xml); do 
+function die() {
+    echo "$@"
+    exit -1
+}
+
+export -f die
+mkdir -p ~/.logs/my-rfa-locks
+for x in "${dirs[@]}"; do 
     job=$((job + 1))
     job=$((job % jobs))
     (
 	(
+	    cd $x || exit
 	    flock -x 9
-	    cd $x;
 	    bash -c "$@"
-	) 9>~/.logs/my-rfa-$job.log &
+	) 9>~/.logs/my-rfa-locks/$job.lock &
     )
-done
+done | tee ~/.logs/my-rfa.log
