.git-interactive-add.before: should remove empty caches bin/ogv2mp4: add ogv2gif
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/ogv2mp4 b/bin/ogv2mp4
--- a/bin/ogv2mp4
+++ b/bin/ogv2mp4
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
 ogv_file=$(readlink -f "$1")
 shift
-ffmpeg -i "$ogv_file" "$@" -strict -2 "${ogv_file%.ogv}".mp4
+ffmpeg -i "$ogv_file" "$@" -strict -2 "${ogv_file%.ogv}".${b0#*2}
