Twiddle the pdf-for-kindle scripts Bind ~M-g g~ for acroread so that can goto a line using Emacs binding.

diff --git a/bin/pdf-for-kindle b/bin/pdf-for-kindle
--- a/bin/pdf-for-kindle
+++ b/bin/pdf-for-kindle
@@ -2,10 +2,10 @@
 
 set -e
 
-left=18.5mm
-bot=18.5mm
-right=18.5mm
-top=25.0mm
+left=0mm
+bot=0mm
+right=0mm
+top=0mm
 paper=a4
 duplicate=5mm
 scale=1.2
@@ -43,76 +43,76 @@ TEMP=$(getopt -o t:l:r:b:W:H:d:p:s:m:c: -n $(basename $0) -- "$@")
 eval set -- "$TEMP"
 while true; do
     case "$1" in
-	-c)
-	    top=$2
-	    bot=$2
-	    left=$2
-	    right=$2
-	    shift 2
-	    ;;
+        -c)
+            top=$2
+            bot=$2
+            left=$2
+            right=$2
+            shift 2
+            ;;
 
 ## start code-generator "^\\s *#"
     # for x in top bot left right; do
-	# printf "%s\n"  "-${x:0:1})"
-	# printf "%s\n" "$x=\$(sum \$$x \$2)"
-	# printf "%s\n" "shift 2"
-	# printf "%s\n" ";;"
+        # printf "%s\n"  "-${x:0:1})"
+        # printf "%s\n" "$x=\$(sum \$$x \$2)"
+        # printf "%s\n" "shift 2"
+        # printf "%s\n" ";;"
     # done
 ## end code-generator
 ## start generated code
-	-t)
-	    top=$(sum $top $2)
-	    shift 2
-	    ;;
-	-b)
-	    bot=$(sum $bot $2)
-	    shift 2
-	    ;;
-	-l)
-	    left=$(sum $left $2)
-	    shift 2
-	    ;;
-	-r)
-	    right=$(sum $right $2)
-	    shift 2
-	    ;;
+        -t)
+            top=$(sum $top $2)
+            shift 2
+            ;;
+        -b)
+            bot=$(sum $bot $2)
+            shift 2
+            ;;
+        -l)
+            left=$(sum $left $2)
+            shift 2
+            ;;
+        -r)
+            right=$(sum $right $2)
+            shift 2
+            ;;
 
 ## end generated code
 
-	-W)
-	    o_width=$2
-	    o_size=cust
-	    shift 2
-	    ;;
-	-H)
-	    o_size=cust
-	    o_height=$2
-	    shift 2
-	    ;;
+        -W)
+            o_width=$2
+            o_size=cust
+            shift 2
+            ;;
+        -H)
+            o_size=cust
+            o_height=$2
+            shift 2
+            ;;
 
-	-d)
-	    duplicate=$2
-	    shift 2
-	    ;;
-	-p)
-	    paper=$2
-	    shift 2
-	    ;;
-	-s)
-	    scale=$2
-	    shift 2
-	    ;;
-	-m)
-	    max=$2
-	    shift 2
-	    ;;
-	--)
-	    shift
-	    break
-	    ;;
-	*)
-	    die "internal error"
-	    ;;
+        -d)
+            duplicate=$2
+            shift 2
+            ;;
+        -p)
+            paper=$2
+            shift 2
+            ;;
+        -s)
+            scale=$2
+            shift 2
+            ;;
+        -m)
+            max=$2
+            shift 2
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
     esac
 done
 pdf=$1
@@ -153,24 +153,36 @@ test -e $pdf || die "Error: $pdf does not exist";
 
 pdf=${pdf%.pdf}
 
+pages=$(pdfinfo "$pdf".pdf | grep "Pages:" | pn 2)
+
 pdfnup --no-landscape --nup 1x1 --papersize "{$n_width,$n_height}"           --trim "$left $bot $right $top" "$pdf".pdf
 cp "$pdf"-nup.pdf cut-"$pdf".pdf
-pdfnup --no-landscape --nup 1x1 --papersize "{$n_width,$remaining_n_height}" --trim "0 $cut_n_height 0 0" --suffix top "$pdf"-nup.pdf 
+pdfnup --no-landscape --nup 1x1 --papersize "{$n_width,$remaining_n_height}" --trim "0 $cut_n_height 0 0" --suffix top "$pdf"-nup.pdf
 pdfnup --no-landscape --nup 1x1 --papersize "{$n_width,$remaining_n_height}" --trim "0 0 0 $cut_n_height" --suffix bot "$pdf"-nup.pdf
 
 
 x=0;
 
+mkdir -p ~/.logs/locks/pdf-for-kindle/
+
 while true; do
     ((x++)) || true;
     if test $max -gt 0 -a $x -gt $max; then
-	break
+        break
     fi
 
-    if ! pdfjoin "$pdf"-nup-top.pdf $x "$pdf"-nup-bot.pdf $x; then
-	break
+    if test $x -gt $pages; then
+        break;
     fi
-done
+
+    ((lock = x % 10)) || true
+
+    (
+        flock 9
+        # split the pages
+        pdfjoin "$pdf"-nup-top.pdf $x "$pdf"-nup-bot.pdf $x&
+    ) 9>~/.logs/locks/pdf-for-kindle/$lock
+done | cat
 
 ((y=x-1))
 for x in $(seq 1 $y); do echo "$pdf"-nup-bot-$x-joined.pdf; done|xargs pdfjoin
