bin/get-google-key: allow to get it quickly bin/putclip-android: make it faster
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/putclip-android b/bin/putclip-android
--- a/bin/putclip-android
+++ b/bin/putclip-android
@@ -1,68 +1,78 @@
 #!/bin/bash
-n_devices=$(my-adb devices?|wc -l)
-if test $n_devices -gt 1 -a -e ~/.config/system-config/bhj/weixin-adb-serial; then
-    export ANDROID_SERIAL=$(cat ~/.config/system-config/bhj/weixin-adb-serial)
-elif test "$n_devices" = 1; then
-    export ANDROID_SERIAL=$(my-adb getprop persist.usb.serialno | grep . || my-adb getprop ro.serialno)
+
+set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
 fi
 
-
-function die() {
-    echo Error: "$@"
-    exit -1
-}
-
-if test $(basename $0) = putclip-android; then
-    if test "$PUTCLIP_ANDROID_FILE"; then
-        if test $# != 0; then
-            die "PUTCLIP_ANDROID_FILE set but arg number is $# not 0"
-        fi
-        cat "$PUTCLIP_ANDROID_FILE" |emoji-to-unicode.pl > ~/.cache/system-config/logs/$(basename $0).txt
+abs0=$0
+if ! [[ $abs0 =~ ^/ ]]; then
+    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
+        abs0=$PWD/$abs0
+    elif test -e "$(which $0)"; then
+        abs0=$(which $0)
     else
-        if test "$#" = 0; then
-            set -- "$(ask-for-input-with-emacs)"
-        fi
-        set -- "$(echo "$@")"
-        echo -n "$@" |emoji-to-unicode.pl > ~/.cache/system-config/logs/$(basename $0).txt
+        die "Can't find abs path for $0"
     fi
-    my-adb push ~/.cache/system-config/logs/$(basename $0).txt /sdcard/putclip.txt&
-    if test "$NO_WEIXIN_EMOJI"; then
-        cp ~/.cache/system-config/logs/$(basename $0).txt ~/.cache/system-config/logs/$(basename $0).txt.wx
-    else
-        unicode-to-wx.pl ~/.cache/system-config/logs/$(basename $0).txt > ~/.cache/system-config/logs/$(basename $0).txt.wx
-    fi
-    my-adb push ~/.cache/system-config/logs/$(basename $0).txt.wx /sdcard/putclip-wx.txt
-    my-adb "
-         am startservice --user 0 -n com.bhj.setclip/.PutClipService&
-         for x in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
-             if test -e /sdcard/putclip.txt; then
-                 sleep .1;
-                 echo \$x;
-             else
-                 exit 0;
-             fi;
-         done
-        "
-elif test $(basename $0) = getclip-android -o $(basename $0) = getphone-android; then
-    cmd=$(basename $0)
-    cmd=${cmd%-*}
+fi
 
-    my-adb '
-        rm -f /sdcard/putclip.txt
-        am startservice --user 0 -n com.bhj.setclip/.PutClipService --ei '$cmd' 1 >/dev/null 2>&1&
-        for x in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
-            if test -e /sdcard/putclip.txt; then
-                break;
-            else
-                sleep .1;
-            fi;
-        done
-' | true
-    my-adb pull /sdcard/putclip.txt /tmp/$(basename $0).$$ >/dev/null 2>&1
-    cat /tmp/$(basename $0).$$
-    rm /tmp/$(basename $0).$$
+b0=$(basename $0)
+
+my-adb devices? -1 >/dev/null 2>&1
+
+if test $b0 = putclip-android; then
+    if test "$#" = 0; then
+        set -- "$(ask-for-input-with-emacs)"
+    fi
+    text=$(printf %q "$*")
+
+    command adb shell sh -c "$(
+printf %q  "$(
+cat <<'EOFd79e06b367a3' | . .replace-%% --
+# {%sh-mode%}
+echo <%text%> > /sdcard/putclip.txt
+am startservice --user 0 -n com.bhj.setclip/.PutClipService --ei '$cmd' 1 >/dev/null 2>&1&
+for x in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
+    if test ! -e /sdcard/putclip.txt; then
+        break;
+    else
+        sleep .1;
+    fi;
+done
+# {%/sh-mode%}
+EOFd79e06b367a3
+)"
+)"
+elif test "$b0" = getclip-android -o "$b0" = getphone-android; then
+    cmd="${b0%-*}"
+
+    command adb shell sh -c "$(
+printf %q "$(
+cat <<'EOFb1b66edbb725' | . .replace-%% --
+# {%sh-mode%}
+rm -f /sdcard/putclip.txt
+am startservice --user 0 -n com.bhj.setclip/.PutClipService --ei '<%cmd%>' 1 >/dev/null 2>&1&
+for x in $(seq 1 20); do
+    if test -e /sdcard/putclip.txt; then
+        cat /sdcard/putclip.txt
+        break
+    else
+        sleep .1
+    fi
+done
+# {%/sh-mode%}
+EOFb1b66edbb725
+)"
+)" | tr -d '\r'
+
 elif test $(basename $0) = gettask-android; then
-     my-adb '
+    my-adb '
          rm -f /sdcard/putclip.txt
          am startservice --user 0 -n com.bhj.setclip/.PutClipService --ei gettask 1 >/dev/null 2>&1&
          for x in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
@@ -73,5 +83,5 @@ elif test $(basename $0) = gettask-android; then
                  sleep .1;
              fi;
          done
-' | cat
+'
 fi
