mf

diff --git a/bin/relative-link b/bin/relative-link
--- a/bin/relative-link
+++ b/bin/relative-link
@@ -63,14 +63,15 @@ test -e "$target_dir" || die "ln: target_dir \`$target_dir does not exist"
 old_target_dir=$target_dir;
 target_dir=$(formal-path "$target_dir"|perl -npe 's,/*$,,')
 
+echo -n > ~/.failed-rln
 for x in $(seq 1 $n_targets); do
     source=${args[$x-1]}
     relative_source=$(calc_relative "$source" "$target_dir"/"$target_file")
-    if test -z "target_file"; then
-	echo 1>&2 "$old_target_dir"/"$(basename "$relative_source")" =\> "$relative_source"
-    else
-	echo 1>&2 "$old_target_dir"/"$target_file" =\> "$relative_source"
-    fi
-    ln -s -- "$relative_source" "$target_dir"/"$target_file"
+    # if test -z "target_file"; then
+    # 	echo 1>&2 "$old_target_dir"/"$(basename "$relative_source")" =\> "$relative_source"
+    # else
+    # 	echo 1>&2 "$old_target_dir"/"$target_file" =\> "$relative_source"
+    # fi
+    ln -s -- "$relative_source" "$target_dir"/"$target_file" || printf "ln -sf -- %q %q\n" "$relative_source" "$target_dir"/"$target_file" >> ~/.failed-rln
 done
     
