bin/create-repo-mirror: should use t3 bin/gerrit-show-queue: show who is using the most queue bin/git-get: abstract some code bin/repo-cherry-find-all: should not error output, and warn when repo-path empty bin/repo-cherry-pick-all: should add -x, for pointing out from which commit.
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/repo-cherry-find-all b/bin/repo-cherry-find-all
--- a/bin/repo-cherry-find-all
+++ b/bin/repo-cherry-find-all
@@ -229,6 +229,9 @@ my-rfa -j $jobs '
     fi
     TOP=$ANDROID_TOP;
     log=$TOP/out/diff/$(repo-path|perl -npe "s,/,%,g").log;
+    if [[ $log =~ /\.log$ ]]; then
+        die "Error for $(ap): can not find repo path"
+    fi
     mkdir -p $(dirname $log);
     if test -z "$to_manifest_xml"; then
         if test ! "$remote" -a $local_from = false ; then
@@ -257,7 +260,7 @@ my-rfa -j $jobs '
         exit
     fi
     echo git-change-id-ffable $from $to in $PWD
-    git-change-id-ffable $from $to > $log
+    git-change-id-ffable $from $to > $log || true
     if test $(stat -c %s $log) = 0; then
         rm $log;
     fi;
