.after-push-hook: should run all hooks bin/arg-not-empty: should allow to be sourced bin/gerrit-push-review: add more hints bin/git-change-id-ffable: should not skip any change-ids bin/maildir-delete-dups: should skip cur:2 bin/repo-cherry-find-all: should not use die bin/repo-cherry-pick-all: do not pick too many bin/yes-or-no-p: should allow for ？ gcode/playground/ruby/MyMixin.rb: test mixin gcode/playground/ruby/ldap.rb: do not use itadmin
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/repo-cherry-find-all b/bin/repo-cherry-find-all
--- a/bin/repo-cherry-find-all
+++ b/bin/repo-cherry-find-all
@@ -233,7 +233,8 @@ my-rfa -j $jobs '
     TOP=$ANDROID_TOP;
     log=$TOP/out/diff/$(repo-path|perl -npe "s,/,%,g").log;
     if [[ $log =~ /\.log$ ]]; then
-        die "Error for $(ap): can not find repo path"
+        echo "Error for $(ap): can not find repo path"
+        exit 1
     fi
     mkdir -p $(dirname $log);
     if test -z "$to_manifest_xml"; then
