bin/android-make: try to unset classpath. bin/repo-changes?: when a dir failed... bin/wp: make it work with smb://
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/repo-changes? b/bin/repo-changes?
--- a/bin/repo-changes?
+++ b/bin/repo-changes?
@@ -48,6 +48,7 @@ set -- $(
 
 my-rfa -j 4 -p "$path_pattern" "$@" -- '
 #{%sh%}
+(
 if test "$DEBUG" = true; then
     set -x
     function git()
@@ -138,6 +139,7 @@ if test "$DO_GIT_ST_ONLY" != true -a "$head_rev" != "$rev"; then
 
     fi
 fi
+) || echo "$PWD git failed"
 
 #{%/sh%}
 ' 2>&1 10>~/.logs/repo-changes.lock | (
