try to repo with --depth 1 by default.
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/repo-released-manifest-diff b/bin/repo-released-manifest-diff
--- a/bin/repo-released-manifest-diff
+++ b/bin/repo-released-manifest-diff
@@ -64,7 +64,14 @@ done
 
 
 default_command() {
-    git log -1000 --name-status $git_log_arguments $1..$2 | indent-clipboard -
+    (
+        if test -e .git/shallow; then
+            export GIT_DIR=~/src/android-mirror/$(repo-project).git
+        fi
+        if ! git log -1000 --name-status $git_log_arguments $1..$2; then
+            scm jenkins-err "Error: can't get git log -1000 --name-status $git_log_arguments $1..$2"
+        fi
+    ) | indent-clipboard -
 }
 
 if test -z "$execute_command"; then
