bin/knuth-mode: make sure the generated file is readonly bin/overide/repo: should exit with error bin/repo-fast-sync: allow to re-init only when necessary doc/var/www/html/vmlinux.html: add patch check
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/repo-fast-sync b/bin/repo-fast-sync
--- a/bin/repo-fast-sync
+++ b/bin/repo-fast-sync
@@ -3,17 +3,26 @@
 set -e
 
 ## start code-generator "^\\s *#\\s *"
-# generate-getopt @sync=true
+# generate-getopt @sync=true @do-reset=true
 ## end code-generator
 ## start generated code
 TEMP=$(getopt -o h \
-              --long sync,help,no-sync \
+              --long do-reset,sync,help,no-do-reset,no-sync \
               -n $(basename -- $0) -- "$@")
+do_reset=true
 sync=true
 eval set -- "$TEMP"
 while true; do
     case "$1" in
 
+        --do-reset|--no-do-reset)
+            if test "$1" = --no-do-reset; then
+                do_reset=false
+            else
+                do_reset=true
+            fi
+            shift
+            ;;
         --sync|--no-sync)
             if test "$1" = --no-sync; then
                 sync=false
@@ -27,6 +36,9 @@ while true; do
             echo
             echo
             echo Options and arguments:
+            printf "%06s" " "
+            printf %-24s '--[no-]do-reset'
+            echo
             printf "%06s" " "
             printf %-24s '--[no-]sync'
             echo
@@ -46,43 +58,58 @@ done
 
 ## end generated code
 
+export do_reset
+
 if test "$sync" = true; then
     repo sync -j4 -n -c
+fi
+
+if test ! -d ~/src/empty-git/.git; then
+    mkdir -p ~/src/empty-git;
+    (
+        cd ~/src/empty-git
+        git init .
+    )
 fi
 
 function fast-init-git-repo() {
     skipping=$1
     dir=$2
     if test "$skipping" = skipping -a "$dir"; then
-        if test -d "$dir/.git"; then
-            return 0
-        fi
         mkdir -p "$dir"
         (
             cd "$dir"
-            git init .
             repo_info=$(repo forall . -c 'echo $REPO_PROJECT $REPO_LREV')
             repo_lrev=${repo_info#* }
             repo_project=${repo_info% *}
+            if test "$repo_project" = "$(cat .git/repo-project 2>/dev/null)"; then
+                echo no need to init $PWD
+            else
+                rm .git -rf
+                cp ~/src/empty-git/.git . -al
 
-            repo_path=$(ap)
-            (
-                cd .git
-                tolink=()
-                for x in description hooks info objects rr-cache svn config logs packed-refs refs shallow; do
-                    rm -rf $x
-                    source=$(lookup-file -e .repo)/projects/$repo_path.git/$x
-                    if test -e "$source"; then
-                        tolink=($(readlink -f "$source") ${tolink[@]})
-                    fi
-                done
-                relative-link ${tolink[@]} .
-            )
-            git reset --soft -q ${repo_lrev}
+                repo_path=$(ap)
+                (
+                    cd .git
+                    tolink=()
+                    for x in description hooks info objects rr-cache svn config logs packed-refs refs shallow; do
+                        rm -rf $x
+                        source=$(lookup-file -e .repo)/projects/$repo_path.git/$x
+                        if test -e "$source"; then
+                            tolink=($(readlink -f "$source") ${tolink[@]})
+                        fi
+                    done
+                    relative-link ${tolink[@]} .
+                    echo "$repo_project" > repo-project
+                )
+            fi
+            if test "$do_reset" = true; then
+                git reset --soft -q ${repo_lrev}
+            fi
         )
     fi
 }
 
 export -f fast-init-git-repo
 
-repo forall -c 'true' 2>&1 >/dev/null | xargs -d \\n -P 10 -n 1 bash -c 'set -e; if ! fast-init-git-repo $@; then echo $@ failed; exit -1; fi' true
+repo forall -c 'echo skipping $PWD' 2>&1 | xargs -d \\n -P 10 -n 1 bash -c 'set -e; if ! fast-init-git-repo $@; then echo $@ failed; exit -1; fi' true
