bin/gerrit2org: should not display if I have responded to a task bin/s: should wait longer for s
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/s b/bin/s
--- a/bin/s
+++ b/bin/s
@@ -24,6 +24,7 @@ if test "$DESKTOP_SESSION" = sawfish; then
         if ! flock -n 9; then
             (
                 exec 9>/dev/null
+                echo "Can't lock s: $$" | tee ~/tmp/s.lock ~/tmp/s.lock.$$
                 # bhj-notify s "Can't lock s $(fuser ~/.cache/system-config/logs/s-sawfish-click|xargs ps $$ |tee ~/tmp/s.lock)"
             )
             exit
@@ -31,11 +32,17 @@ if test "$DESKTOP_SESSION" = sawfish; then
         exec 2>~/tmp/s.txt
 
         declare -a start_events
-        max_try=30
+        max_try=50
 
         for x in $(seq 1 $max_try ); do
             start_event=$(sawfish-client -e '(event-name (last-event))'|tr -d \")
             if [[ ${start_event/-Off/-Click} =~ -Click[0-9] ]]; then # double click
+                double_click=true
+                break
+            fi
+
+            if perl -e '$x = -M "$ENV{HOME}/tmp/s.lock" || 5; print STDERR "Got -M date: $x"; exit 1 if ($x > 25.787037037037037e-06); exit 0'; then
+                cat ~/tmp/s.lock 1>&2
                 double_click=true
                 break
             fi
@@ -50,6 +57,7 @@ if test "$DESKTOP_SESSION" = sawfish; then
                 start_event=${start_events[1]}
             fi
         done
+        rm -f ~/tmp/s.lock
     fi
 
     if test "$start_event" = '"F2"'; then
