.sawfishrc: add mm7 support bin/sawfish-show-pointer: add mm7 support
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/sawfish-show-pointer b/bin/sawfish-show-pointer
--- a/bin/sawfish-show-pointer
+++ b/bin/sawfish-show-pointer
@@ -1,2 +1,21 @@
 #!/bin/bash
-sawfish-client -e '(read-event (format nil "%d x %d" (car (query-pointer)) (cdr (query-pointer))))'
+# -*- mode: sawfish -*-
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+me=$(readlink -f "$(which $0)")
+if test ! -e "$me"; then
+die "Can't find out about me"
+exit 1
+fi
+fi
+b0=$(basename $0)
+cat $me | perl -ne 'print if m/<<<</..-1' |perl -ne 'print unless 1..1' |sawfish-client; exit
+(let* ((pos (query-pointer))
+       (x (car pos))
+       (y (cdr pos))
+       (last-key (event-name (last-event))))
+  (if (string= last-key "C-p")
+      (system (format nil "putclip %d %d&" x y))
+    (system (format nil "(getclip; echo 'xdotool mousemove %d %d\nxdotool click 1\n')|putclip&" x y)))
+  (read-event (format nil "%d x %d" (car (query-pointer)) (cdr (query-pointer))))
+  )
