.sawfish/custom: use my own max toggle for multi-head bin/sawfish-move-to-laptop: allow to move to next head/prev head
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/sawfish-move-to-laptop b/bin/sawfish-move-to-laptop
--- a/bin/sawfish-move-to-laptop
+++ b/bin/sawfish-move-to-laptop
@@ -1,8 +1,55 @@
 #!/bin/bash
-if test $(basename $0) = sawfish-move-to-laptop; then
-    h=$(xrandr | grep '\*'|tail -n 1|perl -npe 's,.*\d+x(\d+).*,$1,')
-    h=${h:-1080}
-    sawfish-client -e "(move-window-to (input-focus) 0 $h)"
+
+set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
+
+function move-window-to-x.y() {
+    x_y=$1
+
+    sawfish-client -e "
+    (let ((w (input-focus))
+          (x_y '$x_y))
+      (when w
+        (move-window-to w (car x_y) (cdr x_y))
+        (when (window-maximized-p w)
+          (maximize-window w))))"
+}
+
+if test $b0 = sawfish-move-to-next-screen -o \
+        $b0 = sawfish-move-to-prev-screen; then
+    n_heads=$(sawfish-client  -e '(head-count)')
+    current_offset=$(
+        sawfish-client  -e '(current-head-offset (input-focus))'
+                  )
+    declare -a head_offsets
+    for h in $(seq 0 $((n_heads - 1))); do
+        head_offsets[$h]=$(
+            sawfish-client  -e '(head-offset '$h')'
+                    )
+    done
+
+    for h in $(seq 0 $((n_heads - 1))); do
+        if test "${head_offsets[$h]}" = "$current_offset"; then
+            if test $b0 = sawfish-move-to-next-screen; then
+                head_plus=1
+            else
+                head_plus=-1
+            fi
+
+            h=$(( (h + n_heads + head_plus) % n_heads ))
+            move-window-to-x.y "${head_offsets[$h]}"
+            exit
+        fi
+    done
 else
-    sawfish-client -e '(move-window-to (input-focus) 0 30)'
+    move-window-to-x.y '(0 . 30)'
 fi
