bin/sawfish-destroy-window: allow to delete windows safely
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/sawfish-destroy-window b/bin/sawfish-destroy-window
--- a/bin/sawfish-destroy-window
+++ b/bin/sawfish-destroy-window
@@ -46,7 +46,21 @@ done
 
 ## end generated code
 
-sawfish-client -e "$(cat <<'EOF2dca9b6e46e5' | perl -npe "s:%arg%:$1:g; s:%skip-top%:$skip_top:g"
+set -e
+
+me=$(readlink -f $0)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $0)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+b0=$(basename $0)
+
+sawfish_command=${b0#sawfish-}
+
+sawfish-client -e "$(cat <<'EOF2dca9b6e46e5' | perl -npe "s:%arg%:$1:g; s:%cmd%:$sawfish_command:g; s:%skip-top%:$skip_top:g"
     (let ((skip-top %skip-top%)
           (n-killed 0))
       (mapcar
@@ -54,7 +68,7 @@ sawfish-client -e "$(cat <<'EOF2dca9b6e46e5' | perl -npe "s:%arg%:$1:g; s:%skip-
          (when (string-equal (bhj-window-class w) "%arg%")
            (unless (and skip-top (= n-killed 0))
              (message (format nil "?window: %s; name: %s; class: %s" w (window-name w) (bhj-window-class w)))
-             (destroy-window w))
+             (%cmd% w))
            (setq n-killed (1+ n-killed))))
        (if skip-top
            (reverse (managed-windows))
