.Xresources: Fix fonts and remote term .sawfish/start/merge-xresources: merge X resources .sawfishrc: allow to run a command bin/sawfish-destroy-window: allow to skip the top one bin/terminal-font-change: allow to change font for xterm bin/where: skip src/system-config bin/xclip-to-gclip: from xclip to gclip
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/sawfish-destroy-window b/bin/sawfish-destroy-window
--- a/bin/sawfish-destroy-window
+++ b/bin/sawfish-destroy-window
@@ -1,8 +1,68 @@
 #!/bin/bash
-sawfish-client -e '
-    (mapcar
-        (lambda (w)
-            (when (string-equal (bhj-window-class w) "'$1'")
-              (message (format nil "?window: %s; name: %s; class: %s" w (window-name w) (bhj-window-class w)))
-              (destroy-window w)))
-        (managed-windows))'
+
+# [[file:~/system-config/knuth-mode/sawfish-destroy-window.org::*%E6%9C%80%E7%BB%88%E7%9A%84%E7%89%88%E6%9C%AC%EF%BC%9A][the-ultimate-script]]
+
+set -e
+
+#!/bin/bash
+
+## start code-generator "^\\s *#\\s *"
+# generate-getopt @:skip-top=nil
+## end code-generator
+## start generated code
+TEMP=$(getopt -o h \
+              --long skip-top:,help \
+              -n $(basename -- $0) -- "$@")
+skip_top=nil
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+
+        --skip-top)
+            skip_top=$2
+            shift 2
+            ;;
+        -h|--help)
+            set +x
+            echo
+            echo
+            echo Options and arguments:
+            printf "%06s" " "
+            printf %-24s '--skip-top=SKIP_TOP'
+            echo
+            exit
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
+
+## end generated code
+
+sawfish-client -e "$(cat <<'EOF2dca9b6e46e5' | perl -npe "s:%arg%:$1:g; s:%skip-top%:$skip_top:g"
+    (let ((skip-top %skip-top%)
+          (n-killed 0))
+      (mapcar
+       (lambda (w)
+         (when (string-equal (bhj-window-class w) "%arg%")
+           (unless (and skip-top (= n-killed 0))
+             (message (format nil "?window: %s; name: %s; class: %s" w (window-name w) (bhj-window-class w)))
+             (destroy-window w))
+           (setq n-killed (1+ n-killed))))
+       (if skip-top
+           (reverse (managed-windows))
+         (managed-windows))))
+EOF2dca9b6e46e5
+)"
+# Local Variables: #
+# eval: (read-only-mode 1) #
+# End: #
+
+# the-ultimate-script ends here
