auto

diff --git a/bin/sc b/bin/sc
--- a/bin/sc
+++ b/bin/sc
@@ -1,5 +1,34 @@
 #!/bin/bash
 
+set -e
+
+me=$(readlink -f $BASH_SOURCE)
+if test ! -e "$me"; then
+    me=$(readlink -f "$(which $BASH_SOURCE)")
+    if test ! -e "$me"; then
+        die "Can't find out about me"
+        exit 1
+    fi
+fi
+
+abs0=$BASH_SOURCE
+if ! [[ $abs0 =~ ^/ ]]; then
+    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
+        abs0=$PWD/$abs0
+    elif test -e "$(which $BASH_SOURCE)"; then
+        abs0=$(which $BASH_SOURCE)
+    else
+        die "Can't find abs path for $BASH_SOURCE"
+    fi
+fi
+
+b0=$(basename $BASH_SOURCE)
+
+if test ! -d ~/system-config; then
+    ln -s ${abs0%/bin/sc} ~/
+    ~/system-config/bin/after-co-ln-s.sh || true
+fi
+
 . ~/system-config/etc/force-system-config
 . ~/system-config/.profile
 . ~/system-config/.bashrc
