bin/update-output-cache: allow to not update the cache comparing beagrep index
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/update-output-cache b/bin/update-output-cache
--- a/bin/update-output-cache
+++ b/bin/update-output-cache
@@ -1,6 +1,66 @@
 #!/bin/bash
 
+
+## start code-generator "^\\s *#\\s *"
+# generate-getopt @:compare-mtime
+## end code-generator
+## start generated code
+TEMP=$(getopt -o h \
+              --long compare-mtime:,help \
+              -n $(basename -- $0) -- "$@")
+compare_mtime=
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+
+        --compare-mtime)
+            compare_mtime=$2
+            shift 2
+            ;;
+        -h|--help)
+            set +x
+            echo
+            echo
+            echo Options and arguments:
+            printf "%06s" " "
+            printf %-24s '--compare-mtime=COMPARE_MTIME'
+            echo
+            exit
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            die "internal error"
+            ;;
+    esac
+done
+
+
+## end generated code
+
 cache=$1
+
+if test -e "$cache" -a "$compare_mtime" = beagrep; then
+    need_update=false
+    if (
+        cd ~/.cache/system-config/for-code-reading/$PWD
+        for f in .beagrep/FileAttributesStore.db .java-fallback.*/.beagrep/FileAttributesStore.db; do
+            if test -e $f -a $f -nt $cache; then
+                exit 0 # need update
+            fi
+        done
+        exit 1
+    ); then
+        need_update=true
+    fi
+    if test "$need_update" = false; then
+        exit
+    fi
+fi
+
 shift
 "$@" > "$cache".$$
 mv "$cache".$$ "$cache"
