update do-weekly so that it will open the weekly page after update.

diff --git a/bin/update-confluence b/bin/update-confluence
--- a/bin/update-confluence
+++ b/bin/update-confluence
@@ -5,6 +5,7 @@ if test -e .confluence.rc; then
     . .confluence.rc
 fi
 
+CONFLUENCE_SERV=$(cat $CONF_DIR/.confserv)
 test $# = 0 && cd ~/confluence/
 IFS=$'\n'
 args=("$@")
@@ -19,9 +20,14 @@ for x in "${args[@]}"; do
         cat ~/doc/confluence-tail;
     ) > "$x".$$
 
-    logf=~/.logs/$(basename $0)-$$.log
-    congfu -- -a storePage --title "${x%%.org}" --encoding UTF-8 --file "$x".$$ > $logf 2>&1|| die "Error: see above"
-    cat $logf|grep 'Page has id: '|perl -npe 's/.*Page has id: (\d+).*/$1/'|xargs -I %s bash -x -c "of http://$(cat $CONF_DIR/.confserv)/pages/viewpage.action?pageId=%s"
+    log=~/.logs/$(basename $0).log
+    congfu -- -a storePage --title "${x%%.org}" --encoding UTF-8 --file "$x".$$ > $log 2>&1|| die "Error: see above"
+
+    cat $log|
+    grep 'Page has id: '|
+    perl -npe 's/.*Page has id: (\d+).*/$1/'|
+    xargs -I %s bash -x -c "of http://$(cat $CONF_DIR/.confserv)/pages/viewpage.action?pageId=%s"
+
     congfu -- -a removeAttachment  --title "${x%%.org}" --name "$x".mht
     congfu -- -a addAttachment --title "${x%%.org}" --file "$x".mht --mime text/html
     rm "$x".$$
