auto.
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/overide/repo b/bin/overide/repo
--- a/bin/overide/repo
+++ b/bin/overide/repo
@@ -218,8 +218,15 @@ else
         exit 0
     else
         ret=$?
-        if test "$1" = init -a -e ".repo/local_manifests"; then
-            echo 1>&2 "Warning: you have local_manifest set, might cause error"
+        if test "$1" = init && is-jenkins; then
+            rm -rf .repo/manifest.xml .repo/manifest.xml.old .repo/manifests .repo/manifests.git;
+            echo 1>&2 "Deleted .repo files and retry"
+            if ~/system-config/bin/repo "$@"; then
+                exit 0
+            fi
+        fi
+        if test "$1" = init && find .repo/local_manifests -type f | grep . -q; then
+            echo 1>&2 "Warning: you have local_manifest files, might cause error"
         fi
         exit $ret
     fi
