bin/adb-install-debian: fix it for t2-m bin/android-rsync-phone-ota: make it work for boot.img+busybox bin/cowbuilder-chroot.prepare: install some pkgs bin/do-ssh-add-all: should add public keys in order bin/fix-kernel-mk.pl: for t2-m bin/overide/repo: make it work for full build bin/remote-edit-secure: putclip stopped working? bin/replace-ramdisk: make it work out of box: boot.img + busybox bin/search-for-exec: filter further bin/system-config-update: should install all build pkgs doc/faq-cn.html: faq for system-config
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/overide/repo b/bin/overide/repo
--- a/bin/overide/repo
+++ b/bin/overide/repo
@@ -14,17 +14,19 @@ if test "$JENKINS_SERVER_COOKIE" -o "$HUDSON_COOKIE"; then
             exit 0
         fi
     elif test "$1" = init -a -d .repo/manifests/.git; then
-            echo "repo sync failed?" > .repo/grep-errors.txt
-            (
-                cd .repo/manifests
-                git reset --hard
-                git clean -xfd
-                find . -type f -name '*.xml'|xargs touch /dev/null
-            )
+        my-rfa "git clean -xfd; git reset --hard" || true
+        echo "repo sync failed?" > .repo/grep-errors.txt
+        (
+            cd .repo/manifests
+            git reset --hard
+            git clean -xfd
+            find . -type f -name '*.xml'|xargs touch /dev/null
+        )
     fi
 fi
 
 if test "$1" = sync; then
+    rm .repo/repo-paths -f
     set -- "$@" --no-tags
     time ~/system-config/bin/repo "$@" && my-rfa 'git config remote.$(repo-remote).tagopt --no-tags'
     exit
