Better mail text.
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/overide/repo b/bin/overide/repo
--- a/bin/overide/repo
+++ b/bin/overide/repo
@@ -182,7 +182,7 @@ if test "$1" = sync -a "$(arg1-arg2 -- -h "$@")" = -h -a "$(arg1-arg2 -- --help 
                                                 rm $path .repo/projects/$path.git .repo/project-objects/$project.git -rf
                                             done
                                         ) && ~/system-config/bin/repo "$@" -j2 $projects && (
-                                            mail-cms -e -o "Info: 'found expected/got error:' in jenkins repo sync and fixed: @$temp_retry" ||
+                                            echo "$projects" | mail-cms -i -e -o "Info: 'single project fetch error:' in jenkins repo sync and fixed: @$temp_retry" ||
                                                 true
                                         )
                                 )
