Change the way cd is recorded.

diff --git a/.sawfish/start/05misc b/.sawfish/start/05misc
--- a/.sawfish/start/05misc
+++ b/.sawfish/start/05misc
@@ -45,18 +45,20 @@ for x in ~/external/sawfish/start/*; do
     )
 done
 
-(
-    flock -n 5 || { echo "lock failed for ssh, exit"; exit; }
-    while true; do
-	if ps aux|grep ssh|grep bhj@216 -q; 
-	then
-            true;
-	else
-            ssh -C2qN -D 8080 bhj@216.194.70.6; 
-	fi
-	sleep 2; 
-    done
-) 5> ~/.logs/ssh-bhj@216.194.70.6 &
+if test $USER = bhj; then
+    (
+	flock -n 5 || { echo "lock failed for ssh, exit"; exit; }
+	while true; do
+	    if ps aux|grep ssh|grep bhj@216 -q; 
+	    then
+		true;
+	    else
+		ssh -C2qN -D 8080 bhj@216.194.70.6; 
+	    fi
+	    sleep 2; 
+	done
+    ) 5> ~/.logs/ssh-bhj@216.194.70.6 &
+fi
 
 # for x in /etc/xdg/autostart/*; do
 #     (
