.sawfishrc: mark eog as gnome window bin/Linux/after-check-out.sh: fix path issue for after-check-out.sh bin/Linux/config/install-pkgs: fix installation programs bin/ask-to-sync-org: fix the sync bin/blog: add a m for match, fix p for page bin/my-at: my-at 'now + 1 minutes' bhj-notify hello 'hello world' bin/myscr: fix debug option bin/replace-ramdisk: add a root-adbd so that gao yuan song can root it for them bin/review-login: fix passwd not pasted yet issue bin/sawfish-gimp-stroke: should use gimp to open the file if it's in eog, should stroke if it's already gimp bin/sawfish-search-in-firefox: fix search in firefox, after C-s, wait for the search box bin/sawfish-send-window-event: should consider what if the window is gnome bin/sawfish-top-window: get the class of the top window bin/ssh-to-phone: do not use ssh if not root bin/sync-mobile-org: do not use ssh unless root bin/xdotool-when-keyboard-clear: should fix when the xkbmap is wrong
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/Linux/config/install-pkgs b/bin/Linux/config/install-pkgs
--- a/bin/Linux/config/install-pkgs
+++ b/bin/Linux/config/install-pkgs
@@ -13,7 +13,15 @@ fi
 
 export LC_ALL=C
 export LANG=C
+export retry=1
 while ! sudo apt-get install "$@" -y $packages; do
+    retry=$((retry + 1))
+    if (( retry % 20 == 0)) && yes-or-no-p "I have tried 20 times, should we continue trying to install?"; then
+        true
+    else
+        echo "Failed: package installation not complete. Please ask for help."
+        exit 1
+    fi
     packages=$(arg1-arg2 "$packages" "$(sudo apt-get install "$@" -y $packages 2>&1)");
     echo installing: $packages
 done
@@ -23,6 +31,6 @@ if test $# = 0 || yes-or-no-p -y "install missing packages?"; then
 fi
 if test "$#" = 0; then
     for x in ~/bin/Linux/config/pkgs/*:*; do
-        sudo apt-get install -y "$x" || true
+        sudo apt-get install -y "${x##*/}" || true
     done
 fi
