bin/Linux/after-check-out.sh: make sure the script is completed bin/Linux/config/install-pkgs: fix quit early problem bin/Linux/emacs-install-packages: do not git clone when using the local version bin/adb-backup-gpt: do not select if already set bin/notify-phone-crash: output the logs etc/cron.d/15m/run-at-tasks: log at better location
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/Linux/config/install-pkgs b/bin/Linux/config/install-pkgs
--- a/bin/Linux/config/install-pkgs
+++ b/bin/Linux/config/install-pkgs
@@ -17,11 +17,13 @@ export retry=1
 unset -f sudo
 while ! sudo apt-get install "$@" -y $packages; do
     retry=$((retry + 1))
-    if (( retry % 20 == 0)) && yes-or-no-p "I have tried 20 times, should we continue trying to install?"; then
-        true
-    else
-        echo "Failed: package installation not complete. Please ask for help."
-        exit 1
+    if (( retry % 20 == 0)); then
+        if yes-or-no-p "I have tried 20 times, should we continue trying to install?"; then
+            true
+        else
+            echo "Failed: package installation not complete. Please ask for help."
+            exit 1
+        fi
     fi
     packages=$(arg1-arg2 "$packages" "$(sudo apt-get install "$@" -y $packages 2>&1)");
     echo installing: $packages
