.emacs: try to fix errors in debian system el, browse-key-ring, bbdb .emacs_d/lisp/bhj-autoloads.el: autoloads update .emacs_d/lisp/bhj-defines.el: no need for bbdb de-duplicate bin/Linux/config/install-missing-pkgs: do not install missing pkgs if there are too many bin/Linux/config/upd_system: install texlive only on my own PC bin/Linux/emacs-install-packages: make sure ~/.emacs.d is there already bin/adb-fix-wifi-mac: print the wifi mac bin/adb-picture-to-weixin-chat: add some comments, add some waiting bin/after-co-ln-s.sh: fix ~/.cache created by update-host-ip. fix systemctl not found bin/do-remote-system-config: make sure the password is used; make sure root can connect bin/search-google: can search sf bin/search-google: search sf ticket bin/smbcp: remount the ~/smb if necessary
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/bin/Linux/config/install-missing-pkgs b/bin/Linux/config/install-missing-pkgs
--- a/bin/Linux/config/install-missing-pkgs
+++ b/bin/Linux/config/install-missing-pkgs
@@ -24,9 +24,23 @@ if (m/^Package: (.*)$/) {
             last;
         }
     }
-}')")
+}')" | sort -u)
 
 echo "missing_packages are $missing_packages" >> ~/.logs/$(basename $0).log
+
+if test "$(echo "$missing_packages" | wc -l)" -gt 50; then
+    if yes-or-no-p -y  "There are too many missing packages, check ~/.logs/$(basename $0).log. Stop?"; then
+        exit 1
+    else
+        true
+    fi
+fi
+
+if ask-if-not-bhj -y "$missing_packages
+
+The above packages are missing, try to install them one by one?"; then
+    exit 0
+fi
 
 for x in $missing_packages; do
     sudo apt-get install "$@" -y $x || true
