add confluence handling scripts

diff --git a/bin/linux/congfu-get b/bin/linux/congfu-get
--- a/bin/linux/congfu-get
+++ b/bin/linux/congfu-get
@@ -2,6 +2,15 @@
 set -e
 export confhome=~/confluence/
 
+function quote-array() {
+        printf "$(
+            for x in $(seq 1 "$#"); 
+            do
+                echo -n "%q "
+            done
+        )" "$@"
+}
+
 function congfu() {
     local user=hjbao
     local server=http://bear/confluence
@@ -13,7 +22,7 @@ function congfu() {
         arg=$1
         shift || break
         
-        case arg in 
+        case "$arg" in 
             --user)
                 user=$1
                 shift
@@ -31,11 +40,13 @@ function congfu() {
                 shift
                 ;;
             *)
-                args=("$args[@]" $1)
+                args=("${args[@]}" "$arg" "$1")
                 shift
                 ;;
-
-    confluence.sh --user hjbao --server http://bear/confluence --space "~hjbao"  --password `cat ~/.confpass` "${args[@]}"
+        esac
+    done
+    
+    confluence.sh --user "$user" --server "$server" --space "$space" --password "$password" "${args[@]}" 2>&1
 }
 
 function die() {
@@ -46,32 +57,70 @@ function die() {
 function congfu-get() {
     cd $confhome || die "Error, I can't switch to $confhome";
     git st -s | grep -q . && die "Error, git repo is not clean";
-    congfu -a getPageList|perl -ne 'print if (2..0xffff and m/^\S+$/)'|xargs -d '\n' touch
+    congfu "$@" -a getPageList|perl -ne 'print if (2..0xffff and m/^\S+$/)'|xargs -d '\n' touch
     for x in *; do 
-        congfu -a getSource --title "$x"|perl -ne 'print unless(1..1)' > "$x"
+        congfu "$@" -a getSource --title "$x"|perl -ne 'print unless(1..1)' > "$x"
     done
 }
 
 function congfu-put() {
     cd $confhome || die "Error, I can't switch to $confhome";
-    git st -s | grep -q . || die "Error, git repo is clean, nothing to commit";
+    
+    test -n "$CONGFU_FILES" || git st -s | grep -q . || die "Error, git repo is clean, nothing to commit";
 
-    git st -s | perl -ne \
+    CONGFU_ARGS=("$@")
+    
+    export CONGFU_ARGSTR=$(
+        quote-array "${CONGFU_ARGS[@]}"
+    )
+    
+    # 最好是在这里在也处理参数，但是我们已经有一个函数在处理参数了，所以好像没有这个必要了。
+    # 可是那文件参数该怎么处理呢？
+
+    # 好吧，就用环境变量吧。如果没有设置文件变量，那么我们需要处理的文件就看git status的结果，把每个有改动的文件都放到服务器上。
+    # 如果有设过环境变量，那么我们就把环境变量里的每个文件都放到服务器上。环境变量里应该还可以支持使用标准输入。
+
+    if test -z "$CONGFU_FILES"
+        then
+        
+        git st -s | perl -ne \
 'chomp(); 
 $_ = substr($_, 3); 
 if (m/^"/) { 
     $_ = eval($_);
 }
 print $_ . "\n";
-' | xargs -d '\n' bash -c \
-'. '`basename $0`';
+' 
+    else 
+        eval "CONGFU_FILESARR=( $CONGFU_FILES )";
+        for x in "${CONGFU_FILESARR[@]}"; do 
+            cat -- "$x" > "$x".$$.bak
+            echo "$x".$$.bak
+        done
+    fi| xargs -d '\n' bash -c \
+'. '$0';
+eval "CONGFU_ARGS=( $CONGFU_ARGSTR )";
 for x in "$@"; do 
-    congfu -a storePage --title "$x" --content "$(cat "$x")"
-    git add "$x"
+    congfu "${CONGFU_ARGS[@]}" -a storePage --title "$x" --content "$(cat -- "$x")"
+    git add -- "$x"
     done ' xx
+    for x in *.$$.bak; do 
+        test -e "$x" || break
+        git rm --cached -- "$x";
+        rm -- "$x"
+        # 不要这这里删除这个页面，我们还有用呢！
+        # congfu "$@" -a removePage --title "$x"
+    done
 }
 
-if test "$BASH_SOURCE" = "$0"; then
+function congfu-test() {
+    CONGFU_FILES=- congfu-put "$@"
+    congfu "$@" -a render --title -.$$.bak |perl -ne 'print unless (1..1)' > ~/1.html
+    congfu "$@" -a removePage --title -.$$.bak
+    of ~/1.html
+}
+
+if test "$(readlink -f "$BASH_SOURCE")" = "$(readlink -f "$(which "$0")" )"; then
     "`basename $0`" "$@"
 fi
 
