mf

diff --git a/bin/linux/git-track b/bin/linux/git-track
--- a/bin/linux/git-track
+++ b/bin/linux/git-track
@@ -2,4 +2,12 @@
 set -e
 . ~/.bash_profile
 test $# == 0 && set -- `tbranch`
-git co -t -b "$1" `git remote`/"$1" || (git config branch."$1".merge refs/heads/"$1"; git config branch."$1".remote `git remote`)
+
+if test $# == 1; then
+    remote=`git branch -r|pn 1|grep '/\b'$1'\b$'`
+    remote=`echo "$remote"|perl -npe 's,/.*,,'|sort -u`
+    echo $remote|grep ' ' && die "Error: more than one remote contains $1: $remote"
+    set -- $1 $remote
+fi
+
+git co -t -b $1 $2/$1 || (git config branch."$1".merge refs/heads/"$1"; git config branch."$1".remote $2)
