lib/jkd.user/dup-release-jira: allow to use on other projects
Signed-off-by: Bao Haojun <baohaojun@gmail.com>

diff --git a/lib/jkd/rest b/lib/jkd/rest
--- a/lib/jkd/rest
+++ b/lib/jkd/rest
@@ -114,7 +114,9 @@ if test "${output_format}" = json; then
 fi
 
 for try in $(seq 1 $max_try); do
-    output=$(curl-f -s -u "${scm_jira_user}:${scm_jira_password}" "$j_url" "$@")
+    if ! output=$(curl-f -s -u "${scm_jira_user}:${scm_jira_password}" "$j_url" "$@"); then
+        die "curl failed with output: '$output'"
+    fi
     if test "${output_format}" = json -a -z "${output}"; then
         sleep $((try * 3))
         continue
